//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalSalaryProcessed {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalSalaryProcessed() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalSalaryProcessed", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNI / ID No.
        /// </summary>
        internal static string cni_id_no {
            get {
                return ResourceManager.GetString("cni_id_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact &amp; Address.
        /// </summary>
        internal static string contact_address {
            get {
                return ResourceManager.GetString("contact_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor username or ID.
        /// </summary>
        internal static string executor_username_or_id {
            get {
                return ResourceManager.GetString("executor_username_or_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry defaults to &lt;strong&gt;now + 48h (UTC)&lt;/strong&gt;. Adjust if needed.
        /// </summary>
        internal static string expiry_defaults_to_now_48h_utc_adjust_if_needed {
            get {
                return ResourceManager.GetString("expiry_defaults_to_now_48h_utc_adjust_if_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Ref Id.
        /// </summary>
        internal static string file_ref_id {
            get {
                return ResourceManager.GetString("file_ref_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload Id.
        /// </summary>
        internal static string file_upload_id {
            get {
                return ResourceManager.GetString("file_upload_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill KYC and submit. A temporary payment code will be generated for this non-member.
        /// </summary>
        internal static string fill_kyc_and_submit_a_temporary_payment_code_will_be_generated_for_this_nonmember {
            get {
                return ResourceManager.GetString("fill_kyc_and_submit_a_temporary_payment_code_will_be_generated_for_this_nonmember" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Member Ref/Name or show non-members only.
        /// </summary>
        internal static string filter_by_member_refname_or_show_nonmembers_only {
            get {
                return ResourceManager.GetString("filter_by_member_refname_or_show_nonmembers_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Uploaded/Executed By.
        /// </summary>
        internal static string filter_by_uploadedexecuted_by {
            get {
                return ResourceManager.GetString("filter_by_uploadedexecuted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by who uploaded or executed.
        /// </summary>
        internal static string filter_by_who_uploaded_or_executed {
            get {
                return ResourceManager.GetString("filter_by_who_uploaded_or_executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on a specific branch.
        /// </summary>
        internal static string focus_on_a_specific_branch {
            get {
                return ResourceManager.GetString("focus_on_a_specific_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For non-member payout activation, shows last code + expiry.
        /// </summary>
        internal static string for_nonmember_payout_activation_shows_last_code_expiry {
            get {
                return ResourceManager.GetString("for_nonmember_payout_activation_shows_last_code_expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Salary.
        /// </summary>
        internal static string gross_salary {
            get {
                return ResourceManager.GetString("gross_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Salary.
        /// </summary>
        internal static string g_salary {
            get {
                return ResourceManager.GetString("g_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.Salary vs N.Salary.
        /// </summary>
        internal static string g_salary_vs_nsalary {
            get {
                return ResourceManager.GetString("g_salary_vs_nsalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If empty, server defaults to now + 48h (UTC).
        /// </summary>
        internal static string if_empty_server_defaults_to_now_48h_utc {
            get {
                return ResourceManager.GetString("if_empty_server_defaults_to_now_48h_utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include country code if international.
        /// </summary>
        internal static string include_country_code_if_international {
            get {
                return ResourceManager.GetString("include_country_code_if_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Old Loan.
        /// </summary>
        internal static string is_old_loan {
            get {
                return ResourceManager.GetString("is_old_loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paid.
        /// </summary>
        internal static string is_paid {
            get {
                return ResourceManager.GetString("is_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan 2 – Exceptional.
        /// </summary>
        internal static string loan_2_exceptional {
            get {
                return ResourceManager.GetString("loan_2_exceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan 3 – Elected Staff.
        /// </summary>
        internal static string loan_3_elected_staff {
            get {
                return ResourceManager.GetString("loan_3_elected_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan 4 – Special / Overdraft.
        /// </summary>
        internal static string loan_4_special_overdraft {
            get {
                return ResourceManager.GetString("loan_4_special_overdraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan 8 – Micro.
        /// </summary>
        internal static string loan_8_micro {
            get {
                return ResourceManager.GetString("loan_8_micro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main / Exceptional / Elected / Special / Micro sections render only when values exist.
        /// </summary>
        internal static string main_exceptional_elected_special_micro_sections_render_only_when_values_exist {
            get {
                return ResourceManager.GetString("main_exceptional_elected_special_micro_sections_render_only_when_values_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-members only.
        /// </summary>
        internal static string non_members_only {
            get {
                return ResourceManager.GetString("non_members_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Member Already Activated.
        /// </summary>
        internal static string non_member_already_activated {
            get {
                return ResourceManager.GetString("non_member_already_activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Member Ref.
        /// </summary>
        internal static string non_member_ref {
            get {
                return ResourceManager.GetString("non_member_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Member Reference.
        /// </summary>
        internal static string non_member_reference {
            get {
                return ResourceManager.GetString("non_member_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-member reference detected.
        /// </summary>
        internal static string non_member_reference_detected {
            get {
                return ResourceManager.GetString("non_member_reference_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.Salary.
        /// </summary>
        internal static string n_salary {
            get {
                return ResourceManager.GetString("n_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.Salary is after Savings, Shares, Charges and Standing Order.
        /// </summary>
        internal static string n_salary_is_after_savings_shares_charges_and_standing_order {
            get {
                return ResourceManager.GetString("n_salary_is_after_savings_shares_charges_and_standing_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid vs Pending.
        /// </summary>
        internal static string paid_vs_pending {
            get {
                return ResourceManager.GetString("paid_vs_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Comment.
        /// </summary>
        internal static string payment_comment {
            get {
                return ResourceManager.GetString("payment_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference Shares.
        /// </summary>
        internal static string preference_shares {
            get {
                return ResourceManager.GetString("preference_shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Salary.
        /// </summary>
        internal static string processed_salary {
            get {
                return ResourceManager.GetString("processed_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Salary – Detail.
        /// </summary>
        internal static string processed_salary_detail {
            get {
                return ResourceManager.GetString("processed_salary_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Salary – Details.
        /// </summary>
        internal static string processed_salary_details {
            get {
                return ResourceManager.GetString("processed_salary_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Salary Results.
        /// </summary>
        internal static string processed_salary_results {
            get {
                return ResourceManager.GetString("processed_salary_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided by salary extract.
        /// </summary>
        internal static string provided_by_salary_extract {
            get {
                return ResourceManager.GetString("provided_by_salary_extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason (for audit).
        /// </summary>
        internal static string reason_for_audit {
            get {
                return ResourceManager.GetString("reason_for_audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register / Activate Non-Member &amp; Generate TempPayCode.
        /// </summary>
        internal static string register_activate_nonmember_generate_temppaycode {
            get {
                return ResourceManager.GetString("register_activate_nonmember_generate_temppaycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register &amp; Generate Code.
        /// </summary>
        internal static string register_generate_code {
            get {
                return ResourceManager.GetString("register_generate_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review executed salary entries, filter by branch, operators, member, status, date, and temporary pay-code state.
        /// </summary>
        internal static string review_executed_salary_entries_filter_by_branch_operators_member_status_date_and_temporary_paycode_state {
            get {
                return ResourceManager.GetString("review_executed_salary_entries_filter_by_branch_operators_member_status_date_and_" +
                        "temporary_paycode_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke TempPayCode.
        /// </summary>
        internal static string revoke_temppaycode {
            get {
                return ResourceManager.GetString("revoke_temppaycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoking will immediately invalidate the code. This action is logged.
        /// </summary>
        internal static string revoking_will_immediately_invalidate_the_code_this_action_is_logged {
            get {
                return ResourceManager.GetString("revoking_will_immediately_invalidate_the_code_this_action_is_logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Analysis Result Id.
        /// </summary>
        internal static string salary_analysis_result_id {
            get {
                return ResourceManager.GetString("salary_analysis_result_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Detail Tips.
        /// </summary>
        internal static string salary_detail_tips {
            get {
                return ResourceManager.GetString("salary_detail_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Paid.
        /// </summary>
        internal static string salary_paid {
            get {
                return ResourceManager.GetString("salary_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Id.
        /// </summary>
        internal static string saving_id {
            get {
                return ResourceManager.GetString("saving_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sub-Division.
        /// </summary>
        internal static string select_subdivision {
            get {
                return ResourceManager.GetString("select_subdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show entries with an active TempPayCode or without one (mutually exclusive).
        /// </summary>
        internal static string show_entries_with_an_active_temppaycode_or_without_one_mutually_exclusive {
            get {
                return ResourceManager.GetString("show_entries_with_an_active_temppaycode_or_without_one_mutually_exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Order.
        /// </summary>
        internal static string standing_order {
            get {
                return ResourceManager.GetString("standing_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/End are inclusive.
        /// </summary>
        internal static string startend_are_inclusive {
            get {
                return ResourceManager.GetString("startend_are_inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Code Expires.
        /// </summary>
        internal static string temp_code_expires {
            get {
                return ResourceManager.GetString("temp_code_expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Code Status.
        /// </summary>
        internal static string temp_code_status {
            get {
                return ResourceManager.GetString("temp_code_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Pay Code.
        /// </summary>
        internal static string temp_pay_code {
            get {
                return ResourceManager.GetString("temp_pay_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempPayCode Expiry.
        /// </summary>
        internal static string temp_pay_code_expiry {
            get {
                return ResourceManager.GetString("temp_pay_code_expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempPayCode Id.
        /// </summary>
        internal static string temp_pay_code_id {
            get {
                return ResourceManager.GetString("temp_pay_code_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry already has an active TempPayCode. You may revoke it below.
        /// </summary>
        internal static string this_entry_already_has_an_active_temppaycode_you_may_revoke_it_below {
            get {
                return ResourceManager.GetString("this_entry_already_has_an_active_temppaycode_you_may_revoke_it_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for filtering processed salary.
        /// </summary>
        internal static string tips_for_filtering_processed_salary {
            get {
                return ResourceManager.GetString("tips_for_filtering_processed_salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded/Executed by.
        /// </summary>
        internal static string uploaded_executed_by {
            get {
                return ResourceManager.GetString("uploaded_executed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader username or ID.
        /// </summary>
        internal static string uploader_username_or_id {
            get {
                return ResourceManager.GetString("uploader_username_or_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the filters below to refine results, then Apply or Export.
        /// </summary>
        internal static string use_the_filters_below_to_refine_results_then_apply_or_export {
            get {
                return ResourceManager.GetString("use_the_filters_below_to_refine_results_then_apply_or_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What’s left after all deductions.
        /// </summary>
        internal static string whats_left_after_all_deductions {
            get {
                return ResourceManager.GetString("whats_left_after_all_deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why are you revoking this code.
        /// </summary>
        internal static string why_are_you_revoking_this_code {
            get {
                return ResourceManager.GetString("why_are_you_revoking_this_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Active TempPayCode only.
        /// </summary>
        internal static string without_active_temppaycode_only {
            get {
                return ResourceManager.GetString("without_active_temppaycode_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Active TempPayCode only.
        /// </summary>
        internal static string with_active_temppaycode_only {
            get {
                return ResourceManager.GetString("with_active_temppaycode_only", resourceCulture);
            }
        }
    }
}
