//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalSalaryExecution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalSalaryExecution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalSalaryExecution", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account impact.
        /// </summary>
        internal static string AccountImpact {
            get {
                return ResourceManager.GetString("AccountImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address anomalies like overpayments or missing records promptly.
        /// </summary>
        internal static string AddressAnomaliesLikeOverpayments {
            get {
                return ResourceManager.GetString("AddressAnomaliesLikeOverpayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed Salary Upload Form.
        /// </summary>
        internal static string AnalyzedSalaryUploadForm {
            get {
                return ResourceManager.GetString("AnalyzedSalaryUploadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzed Salary Upload Management.
        /// </summary>
        internal static string AnalyzedSalaryUploadManagement {
            get {
                return ResourceManager.GetString("AnalyzedSalaryUploadManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid incorrect **Matricule, Salary Codes, or missing details** in the modified file.
        /// </summary>
        internal static string AvoidIncorrectMatriculeSalaryCodesOrMissingDetails {
            get {
                return ResourceManager.GetString("AvoidIncorrectMatriculeSalaryCodesOrMissingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button to analyze uploaded salary data.
        /// </summary>
        internal static string buttonToAnalyzeUploadedSalaryData {
            get {
                return ResourceManager.GetString("buttonToAnalyzeUploadedSalaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button to check previously analyzed results.
        /// </summary>
        internal static string buttonToCheckPreviouslyAnalyzedResults {
            get {
                return ResourceManager.GetString("buttonToCheckPreviouslyAnalyzedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges.
        /// </summary>
        internal static string Charges {
            get {
                return ResourceManager.GetString("Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on.
        /// </summary>
        internal static string ClickOn {
            get {
                return ResourceManager.GetString("ClickOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the.
        /// </summary>
        internal static string ClickThe {
            get {
                return ResourceManager.GetString("ClickThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debits the total salary amount from the selected source account and credits the members&apos; accounts.
        /// </summary>
        internal static string DebitsTheTotalSalaryAmountFromTheSelectedSourceAccount {
            get {
                return ResourceManager.GetString("DebitsTheTotalSalaryAmountFromTheSelectedSourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete invalid uploads to maintain clean and accurate records.
        /// </summary>
        internal static string DeleteInvalidUploadsToMaintainClean {
            get {
                return ResourceManager.GetString("DeleteInvalidUploadsToMaintainClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit analyzed salary records for corrections or updates when necessary.
        /// </summary>
        internal static string EditAnalyzedSalaryRecordsForCorrections {
            get {
                return ResourceManager.GetString("EditAnalyzedSalaryRecordsForCorrections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure all uploaded salary files are accurate and in the correct format.
        /// </summary>
        internal static string EnsureAllUploadedSalaryFilesAreAccurate {
            get {
                return ResourceManager.GetString("EnsureAllUploadedSalaryFilesAreAccurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure modifications match the **original format** to prevent mapping errors.
        /// </summary>
        internal static string EnsureModificationsMatchTheOriginalFormat {
            get {
                return ResourceManager.GetString("EnsureModificationsMatchTheOriginalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure sufficient funds are available in the source account for salary and standing order payments.
        /// </summary>
        internal static string EnsureSufficientFundsAreAvailable {
            get {
                return ResourceManager.GetString("EnsureSufficientFundsAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure uploaded files match payroll records.
        /// </summary>
        internal static string EnsureUploadedFilesMatchPayrollRecords {
            get {
                return ResourceManager.GetString("EnsureUploadedFilesMatchPayrollRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute salary.
        /// </summary>
        internal static string ExecuteSalary {
            get {
                return ResourceManager.GetString("ExecuteSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution reason.
        /// </summary>
        internal static string ExecutionReason {
            get {
                return ResourceManager.GetString("ExecutionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File category.
        /// </summary>
        internal static string FileCategory {
            get {
                return ResourceManager.GetString("FileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload reference.
        /// </summary>
        internal static string FileUploadReference {
            get {
                return ResourceManager.GetString("FileUploadReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT TIPS.
        /// </summary>
        internal static string IMPORTANT_TIPS {
            get {
                return ResourceManager.GetString("IMPORTANT_TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.INT.
        /// </summary>
        internal static string L_INT {
            get {
                return ResourceManager.GetString("L_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.Rep.
        /// </summary>
        internal static string L_Rep {
            get {
                return ResourceManager.GetString("L_Rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.VAT.
        /// </summary>
        internal static string L_VAT {
            get {
                return ResourceManager.GetString("L_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        internal static string Matricule {
            get {
                return ResourceManager.GetString("Matricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor the **status of uploaded files** to track verification and approval stages.
        /// </summary>
        internal static string MonitorTheStatusOfUploadedFiles {
            get {
                return ResourceManager.GetString("MonitorTheStatusOfUploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No salary uploads found.
        /// </summary>
        internal static string NoSalaryUploadsFound {
            get {
                return ResourceManager.GetString("NoSalaryUploadsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.Salary.
        /// </summary>
        internal static string NSalary {
            get {
                return ResourceManager.GetString("NSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes automatic transfers for members with linked standing orders.
        /// </summary>
        internal static string ProcessesAutomaticTransfersForMembersWithLinkedStandingOrders {
            get {
                return ResourceManager.GetString("ProcessesAutomaticTransfersForMembersWithLinkedStandingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Shares.
        /// </summary>
        internal static string PShares {
            get {
                return ResourceManager.GetString("PShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Shares.
        /// </summary>
        internal static string P_Shares {
            get {
                return ResourceManager.GetString("P_Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularly verify analyzed results against payroll to ensure accuracy.
        /// </summary>
        internal static string RegularlyVerifyAnalyzedResults {
            get {
                return ResourceManager.GetString("RegularlyVerifyAnalyzedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove outdated or incorrect files with caution.
        /// </summary>
        internal static string RemoveOutdatedOrIncorrectFilesWithCaution {
            get {
                return ResourceManager.GetString("RemoveOutdatedOrIncorrectFilesWithCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve uploaded files anytime for reference.
        /// </summary>
        internal static string RetrieveUploadedFilesAnytimeForReference {
            get {
                return ResourceManager.GetString("RetrieveUploadedFilesAnytimeForReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks.
        /// </summary>
        internal static string Risks {
            get {
                return ResourceManager.GetString("Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Salary Analysis.
        /// </summary>
        internal static string RunSalaryAnalysis {
            get {
                return ResourceManager.GetString("RunSalaryAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary analysis.
        /// </summary>
        internal static string SalaryAnalysis {
            get {
                return ResourceManager.GetString("SalaryAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary processing.
        /// </summary>
        internal static string SalaryProcessing {
            get {
                return ResourceManager.GetString("SalaryProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALARY EXECUTION.
        /// </summary>
        internal static string SALARY_EXECUTION {
            get {
                return ResourceManager.GetString("SALARY_EXECUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALARY SUMMARY.
        /// </summary>
        internal static string SALARY_SUMMARY {
            get {
                return ResourceManager.GetString("SALARY_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        internal static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an account.
        /// </summary>
        internal static string SelectAnAccount {
            get {
                return ResourceManager.GetString("SelectAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an analysed file to re-upload.
        /// </summary>
        internal static string SelectAnAnalysedFileToReUpload {
            get {
                return ResourceManager.GetString("SelectAnAnalysedFileToReUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a system analysed file.
        /// </summary>
        internal static string SelectASystemAnalysedFile {
            get {
                return ResourceManager.GetString("SelectASystemAnalysedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select modify analysed salary file to map with the system analyzed selected above.
        /// </summary>
        internal static string SelectModifyAnalysedSalaryFileToMapWithTheSystemAnalyzedSelectedAbove {
            get {
                return ResourceManager.GetString("SelectModifyAnalysedSalaryFileToMapWithTheSystemAnalyzedSelectedAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source account.
        /// </summary>
        internal static string SelectSourceAccount {
            get {
                return ResourceManager.GetString("SelectSourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Select the correct system-analyzed file** from the list before uploading the modified version.
        /// </summary>
        internal static string SelectTheCorrectSystemAnalyzedFile {
            get {
                return ResourceManager.GetString("SelectTheCorrectSystemAnalyzedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.Order.
        /// </summary>
        internal static string SOrder {
            get {
                return ResourceManager.GetString("SOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing orders.
        /// </summary>
        internal static string StandingOrders {
            get {
                return ResourceManager.GetString("StandingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected source account will be debited to cover both salary payments and standing orders.
        /// </summary>
        internal static string TheSelectedSourceAccountWillBeDebited {
            get {
                return ResourceManager.GetString("TheSelectedSourceAccountWillBeDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone. Please verify all details before proceeding.
        /// </summary>
        internal static string ThisActionCannotBeUndone {
            get {
                return ResourceManager.GetString("ThisActionCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS.
        /// </summary>
        internal static string TIPS {
            get {
                return ResourceManager.GetString("TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips &amp; Best Practices.
        /// </summary>
        internal static string TipsBestPractices {
            get {
                return ResourceManager.GetString("TipsBestPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to check existing analyzed salary files.
        /// </summary>
        internal static string toCheckExistingAnalyzedSalaryFiles {
            get {
                return ResourceManager.GetString("toCheckExistingAnalyzedSalaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total charges.
        /// </summary>
        internal static string TotalCharges {
            get {
                return ResourceManager.GetString("TotalCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total loan interest.
        /// </summary>
        internal static string TotalLoanInterest {
            get {
                return ResourceManager.GetString("TotalLoanInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total loan repayment.
        /// </summary>
        internal static string TotalLoanRepayment {
            get {
                return ResourceManager.GetString("TotalLoanRepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total members.
        /// </summary>
        internal static string TotalMembers {
            get {
                return ResourceManager.GetString("TotalMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total net salary.
        /// </summary>
        internal static string TotalNetSalary {
            get {
                return ResourceManager.GetString("TotalNetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total preference shares.
        /// </summary>
        internal static string TotalPreferenceShares {
            get {
                return ResourceManager.GetString("TotalPreferenceShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total savings.
        /// </summary>
        internal static string TotalSavings {
            get {
                return ResourceManager.GetString("TotalSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shares.
        /// </summary>
        internal static string TotalShares {
            get {
                return ResourceManager.GetString("TotalShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total standing order amount.
        /// </summary>
        internal static string TotalStandingOrderAmount {
            get {
                return ResourceManager.GetString("TotalStandingOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload analyzed salary file.
        /// </summary>
        internal static string UploadAnalyzedSalaryFile {
            get {
                return ResourceManager.GetString("UploadAnalyzedSalaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and manage **system-analyzed salary files** for verification and modifications before processing final payroll updates.
        /// </summary>
        internal static string UploadAndManageSystemAnalyzedSalaryFiles {
            get {
                return ResourceManager.GetString("UploadAndManageSystemAnalyzedSalaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded by.
        /// </summary>
        internal static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded files.
        /// </summary>
        internal static string UploadedFiles {
            get {
                return ResourceManager.GetString("UploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded on.
        /// </summary>
        internal static string UploadedOn {
            get {
                return ResourceManager.GetString("UploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded salary files.
        /// </summary>
        internal static string UploadedSalaryFiles {
            get {
                return ResourceManager.GetString("UploadedSalaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload, manage, and review salary files seamlessly. Use the options below to upload new files or access existing ones.
        /// </summary>
        internal static string UploadManageAndReviewSalaryFilesSeamlessly {
            get {
                return ResourceManager.GetString("UploadManageAndReviewSalaryFilesSeamlessly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new analyzed file.
        /// </summary>
        internal static string UploadNewAnalyzedFile {
            get {
                return ResourceManager.GetString("UploadNewAnalyzedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use search filters to quickly locate specific employee salary records.
        /// </summary>
        internal static string UseSearchFiltersToQuicklyLocateSpecificEmployeeSalaryRecords {
            get {
                return ResourceManager.GetString("UseSearchFiltersToQuicklyLocateSpecificEmployeeSalaryRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the.
        /// </summary>
        internal static string UseThe {
            get {
                return ResourceManager.GetString("UseThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify regularly.
        /// </summary>
        internal static string VerifyRegularly {
            get {
                return ResourceManager.GetString("VerifyRegularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, analyze, and manage employee salary summaries efficiently. Use the tools below to analyze salary data or view existing records.
        /// </summary>
        internal static string ViewAnalyzeAndManageEmployeeSalary {
            get {
                return ResourceManager.GetString("ViewAnalyzeAndManageEmployeeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View file records and insights.
        /// </summary>
        internal static string ViewFileRecordsAndInsights {
            get {
                return ResourceManager.GetString("ViewFileRecordsAndInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View files.
        /// </summary>
        internal static string ViewFiles {
            get {
                return ResourceManager.GetString("ViewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Result Of Analyzed Salary.
        /// </summary>
        internal static string ViewResultOfAnalyzedSalary {
            get {
                return ResourceManager.GetString("ViewResultOfAnalyzedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View uploaded files.
        /// </summary>
        internal static string ViewUploadedFiles {
            get {
                return ResourceManager.GetString("ViewUploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to execute salary payments and process standing orders. Please review the details before confirming.
        /// </summary>
        internal static string YouAreAboutToExecuteSalaryPayments {
            get {
                return ResourceManager.GetString("YouAreAboutToExecuteSalaryPayments", resourceCulture);
            }
        }
    }
}
