//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalReconciliation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalReconciliation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalReconciliation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type Selected.
        /// </summary>
        internal static string account_type_selected {
            get {
                return ResourceManager.GetString("account_type_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All steps must be completed in sequence.
        /// </summary>
        internal static string all_steps_must_be_completed_in_sequence {
            get {
                return ResourceManager.GetString("all_steps_must_be_completed_in_sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances are already reconciled.
        /// </summary>
        internal static string balances_are_already_reconciled {
            get {
                return ResourceManager.GetString("balances_are_already_reconciled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances are fetched in real-time from core systems.
        /// </summary>
        internal static string balances_are_fetched_in_realtime_from_core_systems {
            get {
                return ResourceManager.GetString("balances_are_fetched_in_realtime_from_core_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Comparison.
        /// </summary>
        internal static string balance_comparison {
            get {
                return ResourceManager.GetString("balance_comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a branch to continue and load branch accounts.
        /// </summary>
        internal static string choose_a_branch_to_continue_and_load_branch_accounts {
            get {
                return ResourceManager.GetString("choose_a_branch_to_continue_and_load_branch_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Reconciliation Mode.
        /// </summary>
        internal static string choose_reconciliation_mode {
            get {
                return ResourceManager.GetString("choose_reconciliation_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose surplus or deficit.
        /// </summary>
        internal static string choose_surplus_or_deficit {
            get {
                return ResourceManager.GetString("choose_surplus_or_deficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the branch you want to reconcile.
        /// </summary>
        internal static string choose_the_branch_you_want_to_reconcile {
            get {
                return ResourceManager.GetString("choose_the_branch_you_want_to_reconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the GL account to apply the adjustment.
        /// </summary>
        internal static string choose_the_gl_account_to_apply_the_adjustment {
            get {
                return ResourceManager.GetString("choose_the_gl_account_to_apply_the_adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the mode (Member or Loan), pick the account type and branch, then inspect balances and branch account details.
        /// </summary>
        internal static string choose_the_mode_member_or_loan_pick_the_account_type_and_branch_then_inspect_balances_and_branch_account_details {
            get {
                return ResourceManager.GetString("choose_the_mode_member_or_loan_pick_the_account_type_and_branch_then_inspect_bala" +
                        "nces_and_branch_account_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the specific account type to view balances.
        /// </summary>
        internal static string choose_the_specific_account_type_to_view_balances {
            get {
                return ResourceManager.GetString("choose_the_specific_account_type_to_view_balances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the specific GL account for reconciliation.
        /// </summary>
        internal static string choose_the_specific_gl_account_for_reconciliation {
            get {
                return ResourceManager.GetString("choose_the_specific_gl_account_for_reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete each step sequentially. Use the Get Balance button when ready, and Reset if you need to start over. Reconciliation is only available after balance is loaded.
        /// </summary>
        internal static string complete_each_step_sequentially_use_the_get_balance_button_when_ready_and_reset_if_you_need_to_start_over_reconciliation_is_only_available_after_balance_is_loaded {
            get {
                return ResourceManager.GetString("complete_each_step_sequentially_use_the_get_balance_button_when_ready_and_reset_i" +
                        "f_you_need_to_start_over_reconciliation_is_only_available_after_balance_is_loade" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For personal, business, and mortgage loans.
        /// </summary>
        internal static string for_personal_business_and_mortgage_loans {
            get {
                return ResourceManager.GetString("for_personal_business_and_mortgage_loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For savings, checking, and deposit accounts.
        /// </summary>
        internal static string for_savings_checking_and_deposit_accounts {
            get {
                return ResourceManager.GetString("for_savings_checking_and_deposit_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Balance &amp; Reconcile.
        /// </summary>
        internal static string get_balance_reconcile {
            get {
                return ResourceManager.GetString("get_balance_reconcile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the balance and proceed with reconciliation.
        /// </summary>
        internal static string get_the_balance_and_proceed_with_reconciliation {
            get {
                return ResourceManager.GetString("get_the_balance_and_proceed_with_reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading loan account types.
        /// </summary>
        internal static string loading_loan_account_types {
            get {
                return ResourceManager.GetString("loading_loan_account_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading member account types.
        /// </summary>
        internal static string loading_member_account_types {
            get {
                return ResourceManager.GetString("loading_member_account_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main_Loan, Project_Loans.
        /// </summary>
        internal static string mainloan_projectloans {
            get {
                return ResourceManager.GetString("mainloan_projectloans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Accounts.
        /// </summary>
        internal static string member_accounts {
            get {
                return ResourceManager.GetString("member_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member And Loan Balance Reconciliation.
        /// </summary>
        internal static string member_and_loan_balance_reconciliation {
            get {
                return ResourceManager.GetString("member_and_loan_balance_reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member balance is greater than trial balance.
        /// </summary>
        internal static string member_balance_is_greater_than_trial_balance {
            get {
                return ResourceManager.GetString("member_balance_is_greater_than_trial_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member balance is greater - typically use Surplus.
        /// </summary>
        internal static string member_balance_is_greater_typically_use_surplus {
            get {
                return ResourceManager.GetString("member_balance_is_greater_typically_use_surplus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No adjustment needed.
        /// </summary>
        internal static string no_adjustment_needed {
            get {
                return ResourceManager.GetString("no_adjustment_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Adjustmen.
        /// </summary>
        internal static string reconciliation_adjustmen {
            get {
                return ResourceManager.GetString("reconciliation_adjustmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Details.
        /// </summary>
        internal static string reconciliation_details {
            get {
                return ResourceManager.GetString("reconciliation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Progress.
        /// </summary>
        internal static string reconciliation_progress {
            get {
                return ResourceManager.GetString("reconciliation_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Setup.
        /// </summary>
        internal static string reconciliation_setup {
            get {
                return ResourceManager.GetString("reconciliation_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and confirm reconciliation.
        /// </summary>
        internal static string review_and_confirm_reconciliation {
            get {
                return ResourceManager.GetString("review_and_confirm_reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings, Loan, Teller accounts.
        /// </summary>
        internal static string savings_loan_teller_accounts {
            get {
                return ResourceManager.GetString("savings_loan_teller_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account Type &amp; Get Balance.
        /// </summary>
        internal static string select_account_type_get_balance {
            get {
                return ResourceManager.GetString("select_account_type_get_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an account type to view balance.
        /// </summary>
        internal static string select_an_account_type_to_view_balance {
            get {
                return ResourceManager.GetString("select_an_account_type_to_view_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a branch first to load account types.
        /// </summary>
        internal static string select_a_branch_first_to_load_account_types {
            get {
                return ResourceManager.GetString("select_a_branch_first_to_load_account_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a branch first to load loan account types.
        /// </summary>
        internal static string select_a_branch_first_to_load_loan_account_types {
            get {
                return ResourceManager.GetString("select_a_branch_first_to_load_loan_account_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a loan account type.
        /// </summary>
        internal static string select_a_loan_account_type {
            get {
                return ResourceManager.GetString("select_a_loan_account_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select GL Account for Adjustment.
        /// </summary>
        internal static string select_gl_account_for_adjustment {
            get {
                return ResourceManager.GetString("select_gl_account_for_adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Member for account balances or Loan for loan balances.
        /// </summary>
        internal static string select_member_for_account_balances_or_loan_for_loan_balances {
            get {
                return ResourceManager.GetString("select_member_for_account_balances_or_loan_for_loan_balances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the appropriate GL account.
        /// </summary>
        internal static string select_the_appropriate_gl_account {
            get {
                return ResourceManager.GetString("select_the_appropriate_gl_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account will be used for reconciliation adjustments.
        /// </summary>
        internal static string this_account_will_be_used_for_reconciliation_adjustments {
            get {
                return ResourceManager.GetString("this_account_will_be_used_for_reconciliation_adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial balance is greater than member balance.
        /// </summary>
        internal static string trial_balance_is_greater_than_member_balance {
            get {
                return ResourceManager.GetString("trial_balance_is_greater_than_member_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial balance is greater - typically use Deficit.
        /// </summary>
        internal static string trial_balance_is_greater_typically_use_deficit {
            get {
                return ResourceManager.GetString("trial_balance_is_greater_typically_use_deficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance Reconciliation Result.
        /// </summary>
        internal static string trial_balance_reconciliation_result {
            get {
                return ResourceManager.GetString("trial_balance_reconciliation_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding the Difference.
        /// </summary>
        internal static string understanding_the_difference {
            get {
                return ResourceManager.GetString("understanding_the_difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to quickly check balances and reconcile either a member account or a loan account.
        /// </summary>
        internal static string use_this_page_to_quickly_check_balances_and_reconcile_either_a_member_account_or_a_loan_account {
            get {
                return ResourceManager.GetString("use_this_page_to_quickly_check_balances_and_reconcile_either_a_member_account_or_" +
                        "a_loan_account", resourceCulture);
            }
        }
    }
}
