//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalLoanAdjustmentConsole {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalLoanAdjustmentConsole() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalLoanAdjustmentConsole", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquent Loans with Aging Breakdown.
        /// </summary>
        internal static string delinquent_loans_with_aging_breakdown {
            get {
                return ResourceManager.GetString("delinquent_loans_with_aging_breakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Delinquency Summary by PAR, Gender, and Loan Type.
        /// </summary>
        internal static string loan_delinquency_summary_by_par_gender_and_loan_type {
            get {
                return ResourceManager.GetString("loan_delinquency_summary_by_par_gender_and_loan_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Portfolio with Delinquency Insight.
        /// </summary>
        internal static string loan_portfolio_with_delinquency_insight {
            get {
                return ResourceManager.GetString("loan_portfolio_with_delinquency_insight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Situation Report (Current Performing Loans).
        /// </summary>
        internal static string loan_situation_report_current_performing_loans {
            get {
                return ResourceManager.GetString("loan_situation_report_current_performing_loans", resourceCulture);
            }
        }
    }
}
