//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpenseOtherPayment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpenseOtherPayment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ExpenseOtherPayment", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounting event items.
        /// </summary>
        internal static string AccountingEventItems {
            get {
                return ResourceManager.GetString("AccountingEventItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A meaningful narration or description is vital for accountability and financial clarity..
        /// </summary>
        internal static string AMeaningfulNarrationOrDescriptionIsVitalForAccountabilityAndFinancialClarity {
            get {
                return ResourceManager.GetString("AMeaningfulNarrationOrDescriptionIsVitalForAccountabilityAndFinancialClarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch-Level Config.
        /// </summary>
        internal static string BranchLevelConfig {
            get {
                return ResourceManager.GetString("BranchLevelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Desk Management.
        /// </summary>
        internal static string CashDeskManagement {
            get {
                return ResourceManager.GetString("CashDeskManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash-out payments.
        /// </summary>
        internal static string CashOutPayments {
            get {
                return ResourceManager.GetString("CashOutPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Beneficiary Info.
        /// </summary>
        internal static string ClearBeneficiaryInfo {
            get {
                return ResourceManager.GetString("ClearBeneficiaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denomination Breakdown.
        /// </summary>
        internal static string DenominationBreakdown {
            get {
                return ResourceManager.GetString("DenominationBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each transaction is recorded against a configured.
        /// </summary>
        internal static string EachTransactionIsRecordedAgainstAConfigured {
            get {
                return ResourceManager.GetString("EachTransactionIsRecordedAgainstAConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event item.
        /// </summary>
        internal static string EventItem {
            get {
                return ResourceManager.GetString("EventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For those operations, please use their respective modules..
        /// </summary>
        internal static string ForThoseOperationsPleaseUseTheirRespectiveModules {
            get {
                return ResourceManager.GetString("ForThoseOperationsPleaseUseTheirRespectiveModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger (GL) accounts.
        /// </summary>
        internal static string GeneralLedgerGLAccounts {
            get {
                return ResourceManager.GetString("GeneralLedgerGLAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL account.
        /// </summary>
        internal static string GLAccount {
            get {
                return ResourceManager.GetString("GLAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Posting.
        /// </summary>
        internal static string GLPosting {
            get {
                return ResourceManager.GetString("GLPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to including expenses made to.
        /// </summary>
        internal static string IncludingExpensesMadeTo {
            get {
                return ResourceManager.GetString("IncludingExpensesMadeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Event Item.
        /// </summary>
        internal static string MandatoryEventItem {
            get {
                return ResourceManager.GetString("MandatoryEventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member vs Non-Member.
        /// </summary>
        internal static string MemberVsNonMember {
            get {
                return ResourceManager.GetString("MemberVsNonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narration Matters.
        /// </summary>
        internal static string NarrationMatters {
            get {
                return ResourceManager.GetString("NarrationMatters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-loan and non-withdrawal cash-outs.
        /// </summary>
        internal static string NonLoanAndNonWithdrawalCashOuts {
            get {
                return ResourceManager.GetString("NonLoanAndNonWithdrawalCashOuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-members.
        /// </summary>
        internal static string NonMembers {
            get {
                return ResourceManager.GetString("NonMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-member/staff.
        /// </summary>
        internal static string NonMemberStaff {
            get {
                return ResourceManager.GetString("NonMemberStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only event items authorized for your branch will be visible in the dropdown..
        /// </summary>
        internal static string OnlyEventItemsAuthorizedForYourBranchWillBeVisibleInTheDropdown {
            get {
                return ResourceManager.GetString("OnlyEventItemsAuthorizedForYourBranchWillBeVisibleInTheDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or a.
        /// </summary>
        internal static string OrA {
            get {
                return ResourceManager.GetString("OrA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cash-Out Operations.
        /// </summary>
        internal static string OtherCashOutOperations {
            get {
                return ResourceManager.GetString("OtherCashOutOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Expense Operations.
        /// </summary>
        internal static string OtherExpenseOperations {
            get {
                return ResourceManager.GetString("OtherExpenseOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Expenses.
        /// </summary>
        internal static string OtherExpenses {
            get {
                return ResourceManager.GetString("OtherExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refer to physical cash paid out at the teller desk and recorded directly against.
        /// </summary>
        internal static string RefersToPhysicalCashPaidOut {
            get {
                return ResourceManager.GetString("RefersToPhysicalCashPaidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search required.
        /// </summary>
        internal static string SearchRequired {
            get {
                return ResourceManager.GetString("SearchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting an event item is.
        /// </summary>
        internal static string SelectingAnEventItemIs {
            get {
                return ResourceManager.GetString("SelectingAnEventItemIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual amount disbursed should be broken down using the denomination interface to match the total cash-out..
        /// </summary>
        internal static string TheActualAmountDisbursedShouldBeBrokenDownUsingTheDenominationInterfaceToMatchTheTotalCashOut {
            get {
                return ResourceManager.GetString("TheActualAmountDisbursedShouldBeBrokenDownUsingTheDenominationInterfaceToMatchThe" +
                        "TotalCashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient&apos;s name is required for all transactions—this ensures traceability and reporting accuracy..
        /// </summary>
        internal static string TheRecipientsNameIsRequiredForAllTransactions {
            get {
                return ResourceManager.GetString("TheRecipientsNameIsRequiredForAllTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This interface manages.
        /// </summary>
        internal static string ThisInterfaceManages {
            get {
                return ResourceManager.GetString("ThisInterfaceManages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This interface supports GL-linked.
        /// </summary>
        internal static string ThisInterfaceSupportsGLLinked {
            get {
                return ResourceManager.GetString("ThisInterfaceSupportsGLLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is designed for.
        /// </summary>
        internal static string ThisModuleIsDesignedFor {
            get {
                return ResourceManager.GetString("ThisModuleIsDesignedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tied to the selected.
        /// </summary>
        internal static string TiedToTheSelected {
            get {
                return ResourceManager.GetString("TiedToTheSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips &amp; Guidelines for Other Expense.
        /// </summary>
        internal static string TipsAndGuidelinesForOtherExpense {
            get {
                return ResourceManager.GetString("TipsAndGuidelinesForOtherExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to ensure proper GL mapping and audit trail..
        /// </summary>
        internal static string ToEnsureProperGLMappingAndAuditTrail {
            get {
                return ResourceManager.GetString("ToEnsureProperGLMappingAndAuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUST SOFT CREDIT (TSC).
        /// </summary>
        internal static string TRUSTSOFTCREDITTSC {
            get {
                return ResourceManager.GetString("TRUSTSOFTCREDITTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the radio buttons to indicate whether the recipient is a.
        /// </summary>
        internal static string UseTheRadioButtonsToIndicateWhetherTheRecipientIsA {
            get {
                return ResourceManager.GetString("UseTheRadioButtonsToIndicateWhetherTheRecipientIsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using predefined.
        /// </summary>
        internal static string UsingPredefined {
            get {
                return ResourceManager.GetString("UsingPredefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Cash Desk of.
        /// </summary>
        internal static string WelcomeToTheCashDeskOf {
            get {
                return ResourceManager.GetString("WelcomeToTheCashDeskOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with optional member association. Use other modules for standard member withdrawals or loan disbursements..
        /// </summary>
        internal static string WithOptionalMemberAssociation {
            get {
                return ResourceManager.GetString("WithOptionalMemberAssociation", resourceCulture);
            }
        }
    }
}
