//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CategoryconficResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryconficResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CategoryconficResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Always refresh data to make sure your results are up-to-date..
        /// </summary>
        internal static string Always_refresh_data_to_make_sure_your_results_are_up_to_date {
            get {
                return ResourceManager.GetString("Always_refresh_data_to_make_sure_your_results_are_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price:.
        /// </summary>
        internal static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string Basic_Information {
            get {
                return ResourceManager.GetString("Basic_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Listing.
        /// </summary>
        internal static string Category_Listing {
            get {
                return ResourceManager.GetString("Category_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Settings.
        /// </summary>
        internal static string Category_Settings {
            get {
                return ResourceManager.GetString("Category_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Books.
        /// </summary>
        internal static string Cheque_Books {
            get {
                return ResourceManager.GetString("Cheque_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Book Filters.
        /// </summary>
        internal static string Cheque_Book_Filters {
            get {
                return ResourceManager.GetString("Cheque_Book_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEQUE CATEGORY CONFIGURATION.
        /// </summary>
        internal static string CHEQUE_CATEGORY_CONFIGURATION {
            get {
                return ResourceManager.GetString("CHEQUE_CATEGORY_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Cheque book name.
        /// </summary>
        internal static string egChequebookname {
            get {
                return ResourceManager.GetString("egChequebookname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Structure.
        /// </summary>
        internal static string Fee_Structure {
            get {
                return ResourceManager.GetString("Fee_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter categories based on whether they are centralised or branch-specific..
        /// </summary>
        internal static string Filter_categories_based_on_whether_they_are_centralised_or_branch_specific {
            get {
                return ResourceManager.GetString("Filter_categories_based_on_whether_they_are_centralised_or_branch_specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for cheque categories using full or partial name..
        /// </summary>
        internal static string for_cheque_categories_using_full_or_partial_name {
            get {
                return ResourceManager.GetString("for_cheque_categories_using_full_or_partial_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Here are the details of the selected cheque book category with all relevant information..
        /// </summary>
        internal static string Here_are_the_details_of_the_selected_cheque_book_category_with_all_relevant_information {
            get {
                return ResourceManager.GetString("Here_are_the_details_of_the_selected_cheque_book_category_with_all_relevant_infor" +
                        "mation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCentralised.
        /// </summary>
        internal static string IsCentralised {
            get {
                return ResourceManager.GetString("IsCentralised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance Fee.
        /// </summary>
        internal static string Issuance_Fee {
            get {
                return ResourceManager.GetString("Issuance_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issueance per customer .
        /// </summary>
        internal static string issueance_per_customer {
            get {
                return ResourceManager.GetString("issueance_per_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure category was actually created if not create one first.
        /// </summary>
        internal static string Make_sure_category_was_actually_created_if_not_create_one_first {
            get {
                return ResourceManager.GetString("Make_sure_category_was_actually_created_if_not_create_one_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage cheque book categories, view existing records, and use advanced filters.
        /// </summary>
        internal static string Manage_cheque_book_categories_view_existing_records_and_use_advanced_filters {
            get {
                return ResourceManager.GetString("Manage_cheque_book_categories_view_existing_records_and_use_advanced_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Manage cheque categories Manage system users and apply filters to search by branch  details, user name..
        /// </summary>
        internal static string Manage_cheque_categories_Manage_system_users_and_apply_filters_to_search_by_branch_details_user_name {
            get {
                return ResourceManager.GetString("Manage_cheque_categories_Manage_system_users_and_apply_filters_to_search_by_branc" +
                        "h_details_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Issuance Per Year:.
        /// </summary>
        internal static string Max_Issuance_Per_Year {
            get {
                return ResourceManager.GetString("Max_Issuance_Per_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow by registration period.
        /// </summary>
        internal static string Narrow_by_registration_period {
            get {
                return ResourceManager.GetString("Narrow_by_registration_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow results by category creation period for audit purposes..
        /// </summary>
        internal static string Narrow_results_by_category_creation_period_for_audit_purposes {
            get {
                return ResourceManager.GetString("Narrow_results_by_category_creation_period_for_audit_purposes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow results by organizational branch to check category distribution..
        /// </summary>
        internal static string Narrow_results_by_organizational_branch_to_check_category_distribution {
            get {
                return ResourceManager.GetString("Narrow_results_by_organizational_branch_to_check_category_distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Check Books.
        /// </summary>
        internal static string Number_Of_Check_Books {
            get {
                return ResourceManager.GetString("Number_Of_Check_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. Of Leaves.
        /// </summary>
        internal static string NumOfLeaves {
            get {
                return ResourceManager.GetString("NumOfLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Fee.
        /// </summary>
        internal static string Renewal_Fee {
            get {
                return ResourceManager.GetString("Renewal_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Date Filters.
        /// </summary>
        internal static string ShowDateFilters {
            get {
                return ResourceManager.GetString("ShowDateFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Branch Filter.
        /// </summary>
        internal static string Show_Branch_Filter {
            get {
                return ResourceManager.GetString("Show_Branch_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filters like branch, and  to manage and audit user access effectively..
        /// </summary>
        internal static string Use_filters_like_branch_and_to_manage_and_audit_user_access_effectively {
            get {
                return ResourceManager.GetString("Use_filters_like_branch_and_to_manage_and_audit_user_access_effectively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Category by organizational branch. .
        /// </summary>
        internal static string View_Category_by_organizational_branch {
            get {
                return ResourceManager.GetString("View_Category_by_organizational_branch", resourceCulture);
            }
        }
    }
}
