//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global_LoanDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_LoanDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global_LoanDetails", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral go here.
        /// </summary>
        internal static string CollateralGoesHere {
            get {
                return ResourceManager.GetString("CollateralGoesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commetee validation.
        /// </summary>
        internal static string CommeteeValidation {
            get {
                return ResourceManager.GetString("CommeteeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses go here.
        /// </summary>
        internal static string ExpensesGoHere {
            get {
                return ResourceManager.GetString("ExpensesGoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Collateral.
        /// </summary>
        internal static string LoanCollateral {
            get {
                return ResourceManager.GetString("LoanCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Comments.
        /// </summary>
        internal static string LoanComments {
            get {
                return ResourceManager.GetString("LoanComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan comments goes here.
        /// </summary>
        internal static string LoanCommentsGoHere {
            get {
                return ResourceManager.GetString("LoanCommentsGoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAN DETAILS.
        /// </summary>
        internal static string LoanDetails {
            get {
                return ResourceManager.GetString("LoanDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan files.
        /// </summary>
        internal static string LoanFiles {
            get {
                return ResourceManager.GetString("LoanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan files goes here.
        /// </summary>
        internal static string LoanFilesGoHere {
            get {
                return ResourceManager.GetString("LoanFilesGoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan schedule.
        /// </summary>
        internal static string LoanSchedule {
            get {
                return ResourceManager.GetString("LoanSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan term.
        /// </summary>
        internal static string LoanTerm {
            get {
                return ResourceManager.GetString("LoanTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all loans.
        /// </summary>
        internal static string ViewAllLoans {
            get {
                return ResourceManager.GetString("ViewAllLoans", resourceCulture);
            }
        }
    }
}
