//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global_LoanApplicationCancellation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_LoanApplicationCancellation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global_LoanApplicationCancellation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment.
        /// </summary>
        internal static string AddAComment {
            get {
                return ResourceManager.GetString("AddAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval status.
        /// </summary>
        internal static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelApplication.
        /// </summary>
        internal static string CancelApplication {
            get {
                return ResourceManager.GetString("CancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        internal static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation is final and cannot be reversed once submitted..
        /// </summary>
        internal static string CancellationIsFinal {
            get {
                return ResourceManager.GetString("CancellationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure proper documentation is maintained for the cancellation decision..
        /// </summary>
        internal static string EnsureProperDocumentation {
            get {
                return ResourceManager.GetString("EnsureProperDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP code.
        /// </summary>
        internal static string EnterOTPCode {
            get {
                return ResourceManager.GetString("EnterOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP code from.
        /// </summary>
        internal static string EnterOTPCodeFrom {
            get {
                return ResourceManager.GetString("EnterOTPCodeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS.
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this action only when a loan application must be invalidated due to errors or member requests..
        /// </summary>
        internal static string UseThisActionOnlyWhen {
            get {
                return ResourceManager.GetString("UseThisActionOnlyWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the cancellation reason is clearly stated in the comment section..
        /// </summary>
        internal static string VerifyCancellationReason {
            get {
                return ResourceManager.GetString("VerifyCancellationReason", resourceCulture);
            }
        }
    }
}
