//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BranchAccountRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BranchAccountRessources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BranchAccountRessources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Negativity Management.
        /// </summary>
        internal static string Account_Negativity_Management {
            get {
                return ResourceManager.GetString("Account_Negativity_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Management Account.
        /// </summary>
        internal static string Add_Management_Account {
            get {
                return ResourceManager.GetString("Add_Management_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Negative Balance.
        /// </summary>
        internal static string Allow_Negative_Balance {
            get {
                return ResourceManager.GetString("Allow_Negative_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All negativity changes are logged with user, timestamp, and previous settings.
        /// </summary>
        internal static string All_negativity_changes_are_logged_with_user_timestamp_and_previous_settings {
            get {
                return ResourceManager.GetString("All_negativity_changes_are_logged_with_user_timestamp_and_previous_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply settings to all accounts within a specific class (e.g., Asset, Liability, Equity).
        /// </summary>
        internal static string Apply_settings_to_all_accounts_within_a_specific_class_Asset_Liability_Equity {
            get {
                return ResourceManager.GetString("Apply_settings_to_all_accounts_within_a_specific_class_Asset_Liability_Equity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-filled from the existing account (read-only).
        /// </summary>
        internal static string Auto_filled_from_the_existing_account_read_only {
            get {
                return ResourceManager.GetString("Auto_filled_from_the_existing_account_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Account Details.
        /// </summary>
        internal static string Branch_Account_Details {
            get {
                return ResourceManager.GetString("Branch_Account_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Account Node Setup.
        /// </summary>
        internal static string Branch_Account_Node_Setup {
            get {
                return ResourceManager.GetString("Branch_Account_Node_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Account Class.
        /// </summary>
        internal static string By_Account_Class {
            get {
                return ResourceManager.GetString("By_Account_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Specific Account.
        /// </summary>
        internal static string By_Specific_Account {
            get {
                return ResourceManager.GetString("By_Specific_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain account types (like reserve accounts) may legally require positive balances.
        /// </summary>
        internal static string Certain_account_types_like_reserve_accounts_may_legally_require_positive_balances {
            get {
                return ResourceManager.GetString("Certain_account_types_like_reserve_accounts_may_legally_require_positive_balances" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose All/Active/Inactive — `All` will not filter by active state..
        /// </summary>
        internal static string Choose_All_Active_Inactive_All_will_not_filter_by_active_state {
            get {
                return ResourceManager.GetString("Choose_All_Active_Inactive_All_will_not_filter_by_active_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the accounting class (Asset, Liability, etc.).
        /// </summary>
        internal static string Choose_the_accounting_class {
            get {
                return ResourceManager.GetString("Choose_the_accounting_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what is changing for this update request.
        /// </summary>
        internal static string Choose_what_is_changing_for_this_update_request {
            get {
                return ResourceManager.GetString("Choose_what_is_changing_for_this_update_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the caret to expand or collapse child nodes.
        /// </summary>
        internal static string Click_the_caret_to_expand_or_collapse_child_nodes {
            get {
                return ResourceManager.GetString("Click_the_caret_to_expand_or_collapse_child_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure negative balance allowances for branch accounts by class or specific account.
        /// </summary>
        internal static string Configure_negative_balance_allowances_for_branch_accounts_by_class_or_specific_account {
            get {
                return ResourceManager.GetString("Configure_negative_balance_allowances_for_branch_accounts_by_class_or_specific_ac" +
                        "count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create mode requirements.
        /// </summary>
        internal static string Create_mode_requirements {
            get {
                return ResourceManager.GetString("Create_mode_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling negativity for active accounts may block transactions that would create overdrafts.
        /// </summary>
        internal static string Disabling_negativity_for_active_accounts_may_block_transactions_that_would_create_overdrafts {
            get {
                return ResourceManager.GetString("Disabling_negativity_for_active_accounts_may_block_transactions_that_would_create" +
                        "_overdrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch  Account.
        /// </summary>
        internal static string Edit_Branch_Account {
            get {
                return ResourceManager.GetString("Edit_Branch_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For create requests.
        /// </summary>
        internal static string For_create_requests {
            get {
                return ResourceManager.GetString("For_create_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hierarchical structure for the selected node.
        /// </summary>
        internal static string hierarchical_structure_for_the_selected_node {
            get {
                return ResourceManager.GetString("hierarchical_structure_for_the_selected_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to the correct chart-of-account (affiliate).
        /// </summary>
        internal static string Link_to_the_correct_chart_of_account_affiliate {
            get {
                return ResourceManager.GetString("Link_to_the_correct_chart_of_account_affiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Account Negativity.
        /// </summary>
        internal static string Management_Account_Negativity {
            get {
                return ResourceManager.GetString("Management_Account_Negativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches against affiliate name..
        /// </summary>
        internal static string Matches_against_affiliate_name {
            get {
                return ResourceManager.GetString("Matches_against_affiliate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be empty. Please clear the selection.
        /// </summary>
        internal static string must_be_empty_Please_clear_the_selection {
            get {
                return ResourceManager.GetString("must_be_empty_Please_clear_the_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be left empty when creating a new account.
        /// </summary>
        internal static string must_be_left_empty_when_creating_a_new_account {
            get {
                return ResourceManager.GetString("must_be_left_empty_when_creating_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old values are locked to prevent accidental edits.
        /// </summary>
        internal static string Old_values_are_locked_to_prevent_accidental_edits {
            get {
                return ResourceManager.GetString("Old_values_are_locked_to_prevent_accidental_edits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only enter the new values you want to apply.
        /// </summary>
        internal static string Only_enter_the_new_values_you_want_to_apply {
            get {
                return ResourceManager.GetString("Only_enter_the_new_values_you_want_to_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting badge.
        /// </summary>
        internal static string Posting_badge {
            get {
                return ResourceManager.GetString("Posting_badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting nodes are labelled with a.
        /// </summary>
        internal static string Posting_nodes_are_labelled_with_a {
            get {
                return ResourceManager.GetString("Posting_nodes_are_labelled_with_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a unique.
        /// </summary>
        internal static string Provide_a_unique {
            get {
                return ResourceManager.GetString("Provide_a_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide both English and Français.
        /// </summary>
        internal static string Provide_both_English_and_Français {
            get {
                return ResourceManager.GetString("Provide_both_English_and_Français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularly review negativity settings to prevent unauthorized overdrafts.
        /// </summary>
        internal static string Regularly_review_negativity_settings_to_prevent_unauthorized_overdrafts {
            get {
                return ResourceManager.GetString("Regularly_review_negativity_settings_to_prevent_unauthorized_overdrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required only if Update Type includes.
        /// </summary>
        internal static string Required_only_if_Update_Type_includes {
            get {
                return ResourceManager.GetString("Required_only_if_Update_Type_includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Branch Account Setup.
        /// </summary>
        internal static string Root_Branch_Account_Setup {
            get {
                return ResourceManager.GetString("Root_Branch_Account_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by selecting a branch to view and manage its account negativity settings.
        /// </summary>
        internal static string Start_by_selecting_a_branch_to_view_and_manage_its_account_negativity_settings {
            get {
                return ResourceManager.GetString("Start_by_selecting_a_branch_to_view_and_manage_its_account_negativity_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target individual branch accounts for precise negativity control.
        /// </summary>
        internal static string Target_individual_branch_accounts_for_precise_negativity_control {
            get {
                return ResourceManager.GetString("Target_individual_branch_accounts_for_precise_negativity_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used for editing of branch Name Bothe in english and french.
        /// </summary>
        internal static string This_page_is_used_for_editing_of_branch_Name_Bothe_in_english_and_french {
            get {
                return ResourceManager.GetString("This_page_is_used_for_editing_of_branch_Name_Bothe_in_english_and_french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Branch Account.
        /// </summary>
        internal static string Tips_for_Branch_Account {
            get {
                return ResourceManager.GetString("Tips_for_Branch_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Root Branch Account.
        /// </summary>
        internal static string Tips_for_Root_Branch_Account {
            get {
                return ResourceManager.GetString("Tips_for_Root_Branch_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle date filters to limit by creation range (UTC).
        /// </summary>
        internal static string Toggle_date_filters_to_limit_by_creation_range_UTC {
            get {
                return ResourceManager.GetString("Toggle_date_filters_to_limit_by_creation_range_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to open close all nodes quickly.
        /// </summary>
        internal static string to_open_close_all_nodes_quickly {
            get {
                return ResourceManager.GetString("to_open_close_all_nodes_quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;By Account Class&quot; to apply changes to multiple accounts simultaneously.
        /// </summary>
        internal static string Use_By_Account_Class_to_apply_changes_to_multiple_accounts_simultaneously {
            get {
                return ResourceManager.GetString("Use_By_Account_Class_to_apply_changes_to_multiple_accounts_simultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use full or partial affiliate code for quick lookup..
        /// </summary>
        internal static string Use_full_or_partial_affiliate_code_for_quick_lookup {
            get {
                return ResourceManager.GetString("Use_full_or_partial_affiliate_code_for_quick_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the filters below to search and manage Branch Accounts.
        /// </summary>
        internal static string Use_the_filters_below_to_search_and_manage_Branch_Accounts {
            get {
                return ResourceManager.GetString("Use_the_filters_below_to_search_and_manage_Branch_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to create branch-specific ledger accounts. Ensure the Account Number is unique within the branch and the Affiliate (Chart of Account) is selected correctly.
        /// </summary>
        internal static string Use_this_form_to_create_branch_specific_ledger_accounts_Ensure_the_Account_Number {
            get {
                return ResourceManager.GetString("Use_this_form_to_create_branch_specific_ledger_accounts_Ensure_the_Account_Number" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this form to create branch-specific ledger accounts. Ensure the Account Number is unique within the branch and the Affiliate (Chart of Account) is selected correctly.
        /// </summary>
        internal static string Use_this_form_to_create_branch_specific_ledger_accounts_Ensure_the_Account_Number_is_unique_within_the_branch_and_the_Affiliate_Chart_of_Account_is_selected_correctly {
            get {
                return ResourceManager.GetString("Use_this_form_to_create_branch_specific_ledger_accounts_Ensure_the_Account_Number" +
                        "_is_unique_within_the_branch_and_the_Affiliate_Chart_of_Account_is_selected_corr" +
                        "ectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this tool to manage whether accounts can have negative balances. Disabling negativity prevents overdrafts.
        /// </summary>
        internal static string Use_this_tool_to_manage_whether_accounts_can_have_negative_balances_Disabling_negativity_prevents_overdrafts {
            get {
                return ResourceManager.GetString("Use_this_tool_to_manage_whether_accounts_can_have_negative_balances_Disabling_neg" +
                        "ativity_prevents_overdrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When disabled, accounts must maintain positive balances at all times.
        /// </summary>
        internal static string When_disabled_accounts_must_maintain_positive_balances_at_all_times {
            get {
                return ResourceManager.GetString("When_disabled_accounts_must_maintain_positive_balances_at_all_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, accounts can have negative balances (useful for overdraft facilities).
        /// </summary>
        internal static string When_enabled_accounts_can_have_negative_balances_useful_for_overdraft_facilities {
            get {
                return ResourceManager.GetString("When_enabled_accounts_can_have_negative_balances_useful_for_overdraft_facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, accounts can have negative balances. When disabled, all balances must be positive.
        /// </summary>
        internal static string When_enabled_accounts_can_have_negative_balances_When_disabled_all_balances_must_be_positive {
            get {
                return ResourceManager.GetString("When_enabled_accounts_can_have_negative_balances_When_disabled_all_balances_must_" +
                        "be_positive", resourceCulture);
            }
        }
    }
}
