//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalLoanCommitee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalLoanCommitee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalLoanCommitee", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new committee.
        /// </summary>
        internal static string add_new_committee {
            get {
                return ResourceManager.GetString("add_new_committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add users in to commitee groups.
        /// </summary>
        internal static string add_users_in_to_commitee_groups {
            get {
                return ResourceManager.GetString("add_users_in_to_commitee_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign members to committee.
        /// </summary>
        internal static string assign_members_to_committee {
            get {
                return ResourceManager.GetString("assign_members_to_committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitee name.
        /// </summary>
        internal static string commitee_name {
            get {
                return ResourceManager.GetString("commitee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitee size.
        /// </summary>
        internal static string commitee_size {
            get {
                return ResourceManager.GetString("commitee_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter acceptable number of approvals.
        /// </summary>
        internal static string enter_acceptable_number_of_approvals {
            get {
                return ResourceManager.GetString("enter_acceptable_number_of_approvals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan commitee.
        /// </summary>
        internal static string loan_commitee {
            get {
                return ResourceManager.GetString("loan_commitee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAN COMMITEE CONFIGURATION.
        /// </summary>
        internal static string loan_commitee_configuration {
            get {
                return ResourceManager.GetString("loan_commitee_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan commitee group.
        /// </summary>
        internal static string loan_commitee_group {
            get {
                return ResourceManager.GetString("loan_commitee_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum amount to valide.
        /// </summary>
        internal static string maximum_amount_to_valide {
            get {
                return ResourceManager.GetString("maximum_amount_to_valide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum amount to valide.
        /// </summary>
        internal static string minimum_amount_to_valide {
            get {
                return ResourceManager.GetString("minimum_amount_to_valide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commitee groups are available at the moment.
        /// </summary>
        internal static string no_commitee_groups_are_available_at_the_moment {
            get {
                return ResourceManager.GetString("no_commitee_groups_are_available_at_the_moment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group leader.
        /// </summary>
        internal static string select_group_leader {
            get {
                return ResourceManager.GetString("select_group_leader", resourceCulture);
            }
        }
    }
}
