//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CashDeskCashout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CashDeskCashout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CashDeskCashout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always validate account balance, service fees, and representative information before proceeding..
        /// </summary>
        internal static string AlwaysValidateAccountBalanceServiceFeesAndRepresentativeInformationBeforeProceeding {
            get {
                return ResourceManager.GetString("AlwaysValidateAccountBalanceServiceFeesAndRepresentativeInformationBeforeProceedi" +
                        "ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and provide.
        /// </summary>
        internal static string AndProvide {
            get {
                return ResourceManager.GetString("AndProvide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        internal static string AuditTrail {
            get {
                return ResourceManager.GetString("AuditTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Desk-Cashout.
        /// </summary>
        internal static string CashDeskCashoutTitle {
            get {
                return ResourceManager.GetString("CashDeskCashoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Desk Withdrawal Operations.
        /// </summary>
        internal static string CashDeskWithdrawalOperations {
            get {
                return ResourceManager.GetString("CashDeskWithdrawalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Name.
        /// </summary>
        internal static string CheckName {
            get {
                return ResourceManager.GetString("CheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Number..
        /// </summary>
        internal static string CheckNumber {
            get {
                return ResourceManager.GetString("CheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance.
        /// </summary>
        internal static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONF.
        /// </summary>
        internal static string CONF {
            get {
                return ResourceManager.GetString("CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm &amp; Proceed.
        /// </summary>
        internal static string ConfirmAndProceed {
            get {
                return ResourceManager.GetString("ConfirmAndProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPOSITOR INFORMATION REQUIRED.
        /// </summary>
        internal static string DepositorInformationRequired {
            get {
                return ResourceManager.GetString("DepositorInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure charges, documentation, and identity are properly validated before confirming the transaction..
        /// </summary>
        internal static string EnsureChargesDocumentationAndIdentityAreProperlyValidatedBeforeConfirmingTheTransaction {
            get {
                return ResourceManager.GetString("EnsureChargesDocumentationAndIdentityAreProperlyValidatedBeforeConfirmingTheTrans" +
                        "action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter denominations..
        /// </summary>
        internal static string EnterDenominations {
            get {
                return ResourceManager.GetString("EnterDenominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee..
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for inclusive charges..
        /// </summary>
        internal static string ForInclusiveCharges {
            get {
                return ResourceManager.GetString("ForInclusiveCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Fee..
        /// </summary>
        internal static string FormFee {
            get {
                return ResourceManager.GetString("FormFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form fee + service charge (2% weekday or 2.5% weekend)..
        /// </summary>
        internal static string FormFeePlusServiceCharge {
            get {
                return ResourceManager.GetString("FormFeePlusServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helps track who completed the transaction..
        /// </summary>
        internal static string HelpsTrackWhoCompletedTheTransaction {
            get {
                return ResourceManager.GetString("HelpsTrackWhoCompletedTheTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Tracking.
        /// </summary>
        internal static string IdentityTracking {
            get {
                return ResourceManager.GetString("IdentityTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INC.
        /// </summary>
        internal static string INC {
            get {
                return ResourceManager.GetString("INC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage member cash withdrawal operations (Normal, Special Withdrawal Slip - SWS, or Saving Withdrawal Notification) in TRUST SOFT CREDIT (TSC). Ensure charges, documentation, and identity are properly validated before confirming the transaction..
        /// </summary>
        internal static string ManageMemberCashWithdrawalOperations {
            get {
                return ResourceManager.GetString("ManageMemberCashWithdrawalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Withdrawal.
        /// </summary>
        internal static string NormalWithdrawal {
            get {
                return ResourceManager.GetString("NormalWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only form fee applies (300 XAF Physical / 1,000 XAF Moral)..
        /// </summary>
        internal static string OnlyFormFeeApplies {
            get {
                return ResourceManager.GetString("OnlyFormFeeApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent proof of who deposited funds..
        /// </summary>
        internal static string PermanentProofOfWhoDepositedFunds {
            get {
                return ResourceManager.GetString("PermanentProofOfWhoDepositedFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing transaction, please wait....
        /// </summary>
        internal static string ProcessingTransactionPleaseWait {
            get {
                return ResourceManager.GetString("ProcessingTransactionPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide.
        /// </summary>
        internal static string Provide {
            get {
                return ResourceManager.GetString("Provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Info..
        /// </summary>
        internal static string RepresentativeInfo {
            get {
                return ResourceManager.GetString("RepresentativeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print..
        /// </summary>
        internal static string RePrint {
            get {
                return ResourceManager.GetString("RePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for KYC and AML regulations..
        /// </summary>
        internal static string RequiredForKYCAndAMLRegulations {
            get {
                return ResourceManager.GetString("RequiredForKYCAndAMLRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Withdrawal Notification.
        /// </summary>
        internal static string SavingWithdrawalNotification {
            get {
                return ResourceManager.GetString("SavingWithdrawalNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Withdrawal Slip - SWS.
        /// </summary>
        internal static string SpecialWithdrawalSlipSWS {
            get {
                return ResourceManager.GetString("SpecialWithdrawalSlipSWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWS Withdrawal.
        /// </summary>
        internal static string SWSWithdrawal {
            get {
                return ResourceManager.GetString("SWSWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then.
        /// </summary>
        internal static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete this transaction, please enter the depositor&apos;s full information for regulatory and audit compliance..
        /// </summary>
        internal static string ToCompleteThisTransactionPleaseEnterTheDepositorsFullInformationForRegulatoryAndAuditCompliance {
            get {
                return ResourceManager.GetString("ToCompleteThisTransactionPleaseEnterTheDepositorsFullInformationForRegulatoryAndA" +
                        "uditCompliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to confirm and.
        /// </summary>
        internal static string ToConfirmAnd {
            get {
                return ResourceManager.GetString("ToConfirmAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUST SOFT CREDIT (TSC).
        /// </summary>
        internal static string TRUSTSOFTCREDITTSC {
            get {
                return ResourceManager.GetString("TRUSTSOFTCREDITTSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use one account only with.
        /// </summary>
        internal static string UseOneAccountOnlyWith {
            get {
                return ResourceManager.GetString("UseOneAccountOnlyWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY THIS IS REQUIRED.
        /// </summary>
        internal static string WhyThisIsRequired {
            get {
                return ResourceManager.GetString("WhyThisIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal from Saving (Notification Policy).
        /// </summary>
        internal static string WithdrawalFromSavingNotificationPolicy {
            get {
                return ResourceManager.GetString("WithdrawalFromSavingNotificationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITHDRAWAL OPERATIONS.
        /// </summary>
        internal static string WithdrawalOperations {
            get {
                return ResourceManager.GetString("WithdrawalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITHDRAWAL TIPS &amp; INSTRUCTIONS.
        /// </summary>
        internal static string WithdrawalTipsAndInstructions {
            get {
                return ResourceManager.GetString("WithdrawalTipsAndInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Notification.
        /// </summary>
        internal static string WithNotification {
            get {
                return ResourceManager.GetString("WithNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Notification.
        /// </summary>
        internal static string WithoutNotification {
            get {
                return ResourceManager.GetString("WithoutNotification", resourceCulture);
            }
        }
    }
}
