//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountOpeningRuleModal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountOpeningRuleModal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountOpeningRuleModal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT OPENING RULE SETUP.
        /// </summary>
        internal static string ACCOUNTOPENINGRULESETUP {
            get {
                return ResourceManager.GetString("ACCOUNTOPENINGRULESETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Specific.
        /// </summary>
        internal static string BranchSpecific {
            get {
                return ResourceManager.GetString("BranchSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize rules for each branch individually.
        /// </summary>
        internal static string CustomizeRulesForEachBranchIndividually {
            get {
                return ResourceManager.GetString("CustomizeRulesForEachBranchIndividually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define or update the rules required for account opening per branch and product..
        /// </summary>
        internal static string DefineOrUpdateTheRules {
            get {
                return ResourceManager.GetString("DefineOrUpdateTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce legal form rules and installment permission on account creation.
        /// </summary>
        internal static string EnforceLegalFormRulesAndInstallment {
            get {
                return ResourceManager.GetString("EnforceLegalFormRulesAndInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal form.
        /// </summary>
        internal static string LegalForm {
            get {
                return ResourceManager.GetString("LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinBalance.
        /// </summary>
        internal static string MinBalance {
            get {
                return ResourceManager.GetString("MinBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moral person.
        /// </summary>
        internal static string MoralPerson {
            get {
                return ResourceManager.GetString("MoralPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding.
        /// </summary>
        internal static string Onboarding {
            get {
                return ResourceManager.GetString("Onboarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening control.
        /// </summary>
        internal static string OpeningControl {
            get {
                return ResourceManager.GetString("OpeningControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical person.
        /// </summary>
        internal static string PhysicalPerson {
            get {
                return ResourceManager.GetString("PhysicalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save rule.
        /// </summary>
        internal static string SaveRule {
            get {
                return ResourceManager.GetString("SaveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes, please wait.
        /// </summary>
        internal static string SavingChangesPleaseWait {
            get {
                return ResourceManager.GetString("SavingChangesPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving product.
        /// </summary>
        internal static string SavingProduct {
            get {
                return ResourceManager.GetString("SavingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select branch.
        /// </summary>
        internal static string SelectBranch {
            get {
                return ResourceManager.GetString("SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select product.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set valid minimum and maximum balances per product.
        /// </summary>
        internal static string SetValidMinimumAndMaximumBalances {
            get {
                return ResourceManager.GetString("SetValidMinimumAndMaximumBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY YOU NEED THIS RULE.
        /// </summary>
        internal static string WHYYOUNEEDTHISRULE {
            get {
                return ResourceManager.GetString("WHYYOUNEEDTHISRULE", resourceCulture);
            }
        }
    }
}
