//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalGLSystemReconciliation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalGLSystemReconciliation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalGLSystemReconciliation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Issue to be Raised ?.
        /// </summary>
        internal static string Any_Issue_to_be_Raised {
            get {
                return ResourceManager.GetString("Any_Issue_to_be_Raised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Reference.
        /// </summary>
        internal static string Auxiliary_Reference {
            get {
                return ResourceManager.GetString("Auxiliary_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Vault Verified ?.
        /// </summary>
        internal static string Cash_Vault_Verified {
            get {
                return ResourceManager.GetString("Cash_Vault_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the box to enable branch selection. You can show or hide it as needed..
        /// </summary>
        internal static string Check_the_box_to_enable_branch_selection_You_can_show_or_hide_it_as_needed {
            get {
                return ResourceManager.GetString("Check_the_box_to_enable_branch_selection_You_can_show_or_hide_it_as_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether to view &lt;em&gt;Cash In&lt;/em&gt; or &lt;em&gt;Cash Out&lt;/em&gt; operations..
        /// </summary>
        internal static string Choose_whether_to_view_Cash_In_or_Cash_Out_operations {
            get {
                return ResourceManager.GetString("Choose_whether_to_view_Cash_In_or_Cash_Out_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &lt;em&gt;Search&lt;/em&gt; to load matching results in the table below..
        /// </summary>
        internal static string Click_Search_to_load_matching_results_in_the_table_below {
            get {
                return ResourceManager.GetString("Click_Search_to_load_matching_results_in_the_table_below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Of Day.
        /// </summary>
        internal static string Close_Of_Day {
            get {
                return ResourceManager.GetString("Close_Of_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine filters (e.g., Branch + Date) for more precise results..
        /// </summary>
        internal static string Combine_filters_e_g_Branch_Date_for_more_precise_results {
            get {
                return ResourceManager.GetString("Combine_filters_e_g_Branch_Date_for_more_precise_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information for the selected journal entry. Scroll to view reconciliations, and receipts..
        /// </summary>
        internal static string Detailed_information_for_the_selected_journal_entry_Scroll_to_view_reconciliations_and_receipts {
            get {
                return ResourceManager.GetString("Detailed_information_for_the_selected_journal_entry_Scroll_to_view_reconciliation" +
                        "s_and_receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the JSON payload carefully. Invalid JSON will not be accepted..
        /// </summary>
        internal static string Edit_the_JSON_payload_carefully_Invalid_JSON_will_not_be_accepted {
            get {
                return ResourceManager.GetString("Edit_the_JSON_payload_carefully_Invalid_JSON_will_not_be_accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a reference number or keyword to search for specific transactions..
        /// </summary>
        internal static string Enter_a_reference_number_or_keyword_to_search_for_specific_transactions {
            get {
                return ResourceManager.GetString("Enter_a_reference_number_or_keyword_to_search_for_specific_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export reconciliation records with optional filters and format selection..
        /// </summary>
        internal static string Export_reconciliation_records_with_optional_filters_and_format_selection {
            get {
                return ResourceManager.GetString("Export_reconciliation_records_with_optional_filters_and_format_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter between &lt;em&gt;Temporary&lt;/em&gt; or &lt;em&gt;Reconciled&lt;/em&gt; journal entries..
        /// </summary>
        internal static string Filter_between_Temporary_or_Reconciled_journal_entries {
            get {
                return ResourceManager.GetString("Filter_between_Temporary_or_Reconciled_journal_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER USAGE GUIDE.
        /// </summary>
        internal static string FILTER_USAGE_GUIDE {
            get {
                return ResourceManager.GetString("FILTER_USAGE_GUIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have  All Transactions be Reconciled ?.
        /// </summary>
        internal static string Have_All_Transactions_be_Reconciled {
            get {
                return ResourceManager.GetString("Have_All_Transactions_be_Reconciled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-Branch Confirmed ?.
        /// </summary>
        internal static string Inter_Branch_Confirmed {
            get {
                return ResourceManager.GetString("Inter_Branch_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Sure every Box is Checked before you can Close the Day.
        /// </summary>
        internal static string Make_Sure_every_Box_is_Checked_before_you_can_Close_the_Day {
            get {
                return ResourceManager.GetString("Make_Sure_every_Box_is_Checked_before_you_can_Close_the_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and then check the following boxes carefully:.
        /// </summary>
        internal static string Read_and_then_check_the_following_boxes_carefully {
            get {
                return ResourceManager.GetString("Read_and_then_check_the_following_boxes_carefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciled Journal ID.
        /// </summary>
        internal static string Reconciled_Journal_ID {
            get {
                return ResourceManager.GetString("Reconciled_Journal_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Date Range (Optional).
        /// </summary>
        internal static string Reconciliation_Date_Range {
            get {
                return ResourceManager.GetString("Reconciliation_Date_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation Report Export.
        /// </summary>
        internal static string Reconciliation_Report_Export {
            get {
                return ResourceManager.GetString("Reconciliation_Report_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status for failed reconciled entries.
        /// </summary>
        internal static string Select_status_for_failed_reconciled_entries {
            get {
                return ResourceManager.GetString("Select_status_for_failed_reconciled_entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Reconciliation.
        /// </summary>
        internal static string System_Reconciliation {
            get {
                return ResourceManager.GetString("System_Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM RECONCILIATION DETAILS.
        /// </summary>
        internal static string SYSTEM_RECONCILIATION_DETAILS {
            get {
                return ResourceManager.GetString("SYSTEM_RECONCILIATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp Journal ID.
        /// </summary>
        internal static string Temp_Journa_ID {
            get {
                return ResourceManager.GetString("Temp_Journa_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the reset button to clear all filters and start a new search..
        /// </summary>
        internal static string Use_the_reset_button_to_clear_all_filters_and_start_a_new_search {
            get {
                return ResourceManager.GetString("Use_the_reset_button_to_clear_all_filters_and_start_a_new_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the toggle to show or hide accounting and creation date filters. You can filter by range for better results..
        /// </summary>
        internal static string Use_the_toggle_to_show_or_hide_accounting_and_creation_date_filters_You_can_filter_by_range_for_better_results {
            get {
                return ResourceManager.GetString("Use_the_toggle_to_show_or_hide_accounting_and_creation_date_filters_You_can_filte" +
                        "r_by_range_for_better_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to modify the payload.
        /// </summary>
        internal static string Use_this_page_to_modify_the_payload {
            get {
                return ResourceManager.GetString("Use_this_page_to_modify_the_payload", resourceCulture);
            }
        }
    }
}
