//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalIPSConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalIPSConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalIPSConfig", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bellow we have the Detail Description of an IPS Configuration.
        /// </summary>
        internal static string bellow_we_have_the_Detail_Description_of_an_IPS_Configuration {
            get {
                return ResourceManager.GetString("bellow_we_have_the_Detail_Description_of_an_IPS_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse and filter IPS configurations by year, branch, and other criteria..
        /// </summary>
        internal static string Browse_and_filter_IPS_configurations_by_year_branch_and_other_criteria {
            get {
                return ResourceManager.GetString("Browse_and_filter_IPS_configurations_by_year_branch_and_other_criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure and manage Insurance Premium System settings for different years and branches..
        /// </summary>
        internal static string Configure_and_manage_Insurance_Premium_System_settings_for_different_years_and_branches {
            get {
                return ResourceManager.GetString("Configure_and_manage_Insurance_Premium_System_settings_for_different_years_and_br" +
                        "anches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure different premium rates for loans and savings. Rates are applied as percentages..
        /// </summary>
        internal static string Configure_different_premium_rates_for_loans_and_savings_Rates_are_applied_as_percentages {
            get {
                return ResourceManager.GetString("Configure_different_premium_rates_for_loans_and_savings_Rates_are_applied_as_perc" +
                        "entages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create branch-specific configurations or apply the same settings across all branches..
        /// </summary>
        internal static string Create_branch_specific_configurations_or_apply_the_same_settings_across_all_branches {
            get {
                return ResourceManager.GetString("Create_branch_specific_configurations_or_apply_the_same_settings_across_all_branc" +
                        "hes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define maximum insurance coverage amounts for both loan and savings products..
        /// </summary>
        internal static string Define_maximum_insurance_coverage_amounts_for_both_loan_and_savings_products {
            get {
                return ResourceManager.GetString("Define_maximum_insurance_coverage_amounts_for_both_loan_and_savings_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each configuration is specific to a calendar year. Create separate configurations for different years..
        /// </summary>
        internal static string Each_configuration_is_specific_to_a_calendar_year_Create_separate_configurations_for_different_years {
            get {
                return ResourceManager.GetString("Each_configuration_is_specific_to_a_calendar_year_Create_separate_configurations_" +
                        "for_different_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this option to exclude group accounts from insurance coverage..
        /// </summary>
        internal static string Enable_this_option_to_exclude_group_accounts_from_insurance_coverage {
            get {
                return ResourceManager.GetString("Enable_this_option_to_exclude_group_accounts_from_insurance_coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configurations by Year.
        /// </summary>
        internal static string IPS_Configurations_by_Year {
            get {
                return ResourceManager.GetString("IPS_Configurations_by_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configurations Management.
        /// </summary>
        internal static string IPS_Configurations_Management {
            get {
                return ResourceManager.GetString("IPS_Configurations_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configuration Details.
        /// </summary>
        internal static string IPS_Configuration_Details {
            get {
                return ResourceManager.GetString("IPS_Configuration_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configuration Filters.
        /// </summary>
        internal static string IPS_Configuration_Filters {
            get {
                return ResourceManager.GetString("IPS_Configuration_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configuration Management.
        /// </summary>
        internal static string IPS_Configuration_Management {
            get {
                return ResourceManager.GetString("IPS_Configuration_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Configuration Tips.
        /// </summary>
        internal static string IPS_Configuration_Tips {
            get {
                return ResourceManager.GetString("IPS_Configuration_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPS Config Details.
        /// </summary>
        internal static string IPS_Config_Details {
            get {
                return ResourceManager.GetString("IPS_Config_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Savings Claim Credit Account.
        /// </summary>
        internal static string Life_Savings_Claim_Credit_Account {
            get {
                return ResourceManager.GetString("Life_Savings_Claim_Credit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Savings Claim Debit Account.
        /// </summary>
        internal static string Life_Savings_Claim_Debit_Account {
            get {
                return ResourceManager.GetString("Life_Savings_Claim_Debit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Protection Credit Account.
        /// </summary>
        internal static string Loan_Protection_Credit_Account {
            get {
                return ResourceManager.GetString("Loan_Protection_Credit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Protection Debit Account.
        /// </summary>
        internal static string Loan_Protection_Debit_Account {
            get {
                return ResourceManager.GetString("Loan_Protection_Debit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Delinquency Days From.
        /// </summary>
        internal static string Max_Delinquency_Days_From {
            get {
                return ResourceManager.GetString("Max_Delinquency_Days_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Delinquency Days To.
        /// </summary>
        internal static string Max_Delinquency_Days_To {
            get {
                return ResourceManager.GetString("Max_Delinquency_Days_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple configurations found for the selected year.
        /// </summary>
        internal static string Multiple_configurations_found_for_the_selected_year {
            get {
                return ResourceManager.GetString("Multiple_configurations_found_for_the_selected_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IPS configurations found for the selected year..
        /// </summary>
        internal static string No_IPS_configurations_found_for_the_selected_year {
            get {
                return ResourceManager.GetString("No_IPS_configurations_found_for_the_selected_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active configurations are applied to new insurance policies..
        /// </summary>
        internal static string Only_active_configurations_are_applied_to_new_insurance_policies {
            get {
                return ResourceManager.GetString("Only_active_configurations_are_applied_to_new_insurance_policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select appropriate debit and credit accounts for life savings claims and loan protection transactions..
        /// </summary>
        internal static string Select_appropriate_debit_and_credit_accounts_for_life_savings_claims_and_loan_protection_transactions {
            get {
                return ResourceManager.GetString("Select_appropriate_debit_and_credit_accounts_for_life_savings_claims_and_loan_pro" +
                        "tection_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set coverage limits, premium rates, and eligibility criteria for loan and savings insurance products..
        /// </summary>
        internal static string Set_coverage_limits_premium_rates_and_eligibility_criteria_for_loan_and_savings_insurance_products {
            get {
                return ResourceManager.GetString("Set_coverage_limits_premium_rates_and_eligibility_criteria_for_loan_and_savings_i" +
                        "nsurance_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set maximum customer age for insurance eligibility. Customers beyond this age won&apos;t be covered..
        /// </summary>
        internal static string Set_maximum_customer_age_for_insurance_eligibility_Customers_beyond_this_age_wont_be_covered {
            get {
                return ResourceManager.GetString("Set_maximum_customer_age_for_insurance_eligibility_Customers_beyond_this_age_wont" +
                        "_be_covered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set maximum delinquency days allowed before insurance coverage is suspended..
        /// </summary>
        internal static string Set_maximum_delinquency_days_allowed_before_insurance_coverage_is_suspended {
            get {
                return ResourceManager.GetString("Set_maximum_delinquency_days_allowed_before_insurance_coverage_is_suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the filters below to narrow down the list of IPS configurations..
        /// </summary>
        internal static string Use_the_filters_below_to_narrow_down_the_list_of_IPS_configurations {
            get {
                return ResourceManager.GetString("Use_the_filters_below_to_narrow_down_the_list_of_IPS_configurations", resourceCulture);
            }
        }
    }
}
