//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalFeeConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalFeeConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalFeeConfig", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Percentage.
        /// </summary>
        internal static string AcceptPercentage {
            get {
                return ResourceManager.GetString("AcceptPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Range.
        /// </summary>
        internal static string AcceptRange {
            get {
                return ResourceManager.GetString("AcceptRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Static.
        /// </summary>
        internal static string AcceptStatic {
            get {
                return ResourceManager.GetString("AcceptStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Percentage.
        /// </summary>
        internal static string Accept_Percentage {
            get {
                return ResourceManager.GetString("Accept_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Range.
        /// </summary>
        internal static string Accept_Range {
            get {
                return ResourceManager.GetString("Accept_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Static Amount.
        /// </summary>
        internal static string Accept_Static_Amount {
            get {
                return ResourceManager.GetString("Accept_Static_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        internal static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting scope and a fee type click &apos;Load&apos; to fetch existing settings..
        /// </summary>
        internal static string After_selecting_scope_and_a_fee_type_click_Load_to_fetch_existing_settings {
            get {
                return ResourceManager.GetString("After_selecting_scope_and_a_fee_type_click_Load_to_fetch_existing_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Fee Types.
        /// </summary>
        internal static string All_Fee_Types {
            get {
                return ResourceManager.GetString("All_Fee_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always choose either to configure a centralized system or decentralized and always choose a Fee Type..
        /// </summary>
        internal static string Always_choose_either_to_configure_a_centralized_system_or_decentralized_and_always_choose_a_Fee_Type {
            get {
                return ResourceManager.GetString("Always_choose_either_to_configure_a_centralized_system_or_decentralized_and_alway" +
                        "s_choose_a_Fee_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Specific.
        /// </summary>
        internal static string Branch_Specific {
            get {
                return ResourceManager.GetString("Branch_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Scope.
        /// </summary>
        internal static string ConfigurationScope {
            get {
                return ResourceManager.GetString("ConfigurationScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Type.
        /// </summary>
        internal static string Configuration_Type {
            get {
                return ResourceManager.GetString("Configuration_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Configure centralized or branch-specific fees using percentage or range-based calculations..
        /// </summary>
        internal static string Configure_centralized_or_branch_specific_fees_using_percentage_or_range_based_calculations {
            get {
                return ResourceManager.GetString("Configure_centralized_or_branch_specific_fees_using_percentage_or_range_based_cal" +
                        "culations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete will permanently remove the configuration for the loaded scope..
        /// </summary>
        internal static string Delete_will_permanently_remove_the_configuration_for_the_loaded_scope {
            get {
                return ResourceManager.GetString("Delete_will_permanently_remove_the_configuration_for_the_loaded_scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a Configuration.
        /// </summary>
        internal static string Deleting_a_Configuration {
            get {
                return ResourceManager.GetString("Deleting_a_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Percentage Fee.
        /// </summary>
        internal static string EnablePercentageFee {
            get {
                return ResourceManager.GetString("EnablePercentageFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Range-Based Fee.
        /// </summary>
        internal static string EnableRangeBasedFee {
            get {
                return ResourceManager.GetString("EnableRangeBasedFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Status Fee.
        /// </summary>
        internal static string EnableStatusFee {
            get {
                return ResourceManager.GetString("EnableStatusFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable only one method at a time (Percentage or Range) — UI enforces this..
        /// </summary>
        internal static string Enable_only_one_method_at_a_time_Percentage_or_Range_UI_enforces_this {
            get {
                return ResourceManager.GetString("Enable_only_one_method_at_a_time_Percentage_or_Range_UI_enforces_this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fee ranges defined for this configuration.
        /// </summary>
        internal static string feedetailstext2 {
            get {
                return ResourceManager.GetString("feedetailstext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Ranges.
        /// </summary>
        internal static string FeeRanges {
            get {
                return ResourceManager.GetString("FeeRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Fee Settings.
        /// </summary>
        internal static string FeeSettings {
            get {
                return ResourceManager.GetString("FeeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Value.
        /// </summary>
        internal static string FeeValue {
            get {
                return ResourceManager.GetString("FeeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Config.
        /// </summary>
        internal static string Fee_Config {
            get {
                return ResourceManager.GetString("Fee_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Configurations.
        /// </summary>
        internal static string Fee_Configurations {
            get {
                return ResourceManager.GetString("Fee_Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Configuration Details.
        /// </summary>
        internal static string Fee_Configuration_Details {
            get {
                return ResourceManager.GetString("Fee_Configuration_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Config Details.
        /// </summary>
        internal static string Fee_Config_Details {
            get {
                return ResourceManager.GetString("Fee_Config_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Config Filters.
        /// </summary>
        internal static string Fee_Config_Filters {
            get {
                return ResourceManager.GetString("Fee_Config_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Method Choice.
        /// </summary>
        internal static string Fee_Method_Choice {
            get {
                return ResourceManager.GetString("Fee_Method_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &amp; Sort Configuration.
        /// </summary>
        internal static string Filter_Sort_Configuration {
            get {
                return ResourceManager.GetString("Filter_Sort_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Amount.
        /// </summary>
        internal static string FromAmount {
            get {
                return ResourceManager.GetString("FromAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here we have the details of each fee configuration which is divided into three sections Basic Information, Fee Seting and Fee Ranges.
        /// </summary>
        internal static string here_we_have_the_details_of_each_fee_configuration_which_is_divided_into_three_sections_Basic_Information_Fee_Seting_and_Fee_Ranges {
            get {
                return ResourceManager.GetString("here_we_have_the_details_of_each_fee_configuration_which_is_divided_into_three_se" +
                        "ctions_Basic_Information_Fee_Seting_and_Fee_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Configuration.
        /// </summary>
        internal static string LoadConfiguration {
            get {
                return ResourceManager.GetString("LoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Configuration for.
        /// </summary>
        internal static string ManageConfigurationfor {
            get {
                return ResourceManager.GetString("ManageConfigurationfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Config.
        /// </summary>
        internal static string PercentageConfig {
            get {
                return ResourceManager.GetString("PercentageConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Config.
        /// </summary>
        internal static string RangeConfig {
            get {
                return ResourceManager.GetString("RangeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Name.
        /// </summary>
        internal static string RangeName {
            get {
                return ResourceManager.GetString("RangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this row.
        /// </summary>
        internal static string Remove_this_row {
            get {
                return ResourceManager.GetString("Remove_this_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save button persists the entire configuration..
        /// </summary>
        internal static string Save_button_persists_the_entire_configuration {
            get {
                return ResourceManager.GetString("Save_button_persists_the_entire_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Changes.
        /// </summary>
        internal static string Saving_Changes {
            get {
                return ResourceManager.GetString("Saving_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Configuration Scope.
        /// </summary>
        internal static string SelectConfigurationScope {
            get {
                return ResourceManager.GetString("SelectConfigurationScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string Static {
            get {
                return ResourceManager.GetString("Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Amount.
        /// </summary>
        internal static string StaticAmount {
            get {
                return ResourceManager.GetString("StaticAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Config.
        /// </summary>
        internal static string StaticConfig {
            get {
                return ResourceManager.GetString("StaticConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS FOR FEE CONFIGURATION.
        /// </summary>
        internal static string TIPS_FOR_FEE_CONFIGURATION {
            get {
                return ResourceManager.GetString("TIPS_FOR_FEE_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Amount.
        /// </summary>
        internal static string ToAmount {
            get {
                return ResourceManager.GetString("ToAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;Is Centralized&apos; for system-wide rules; uncheck to pick a branch..
        /// </summary>
        internal static string Use_Is_Centralized_for_system_wide_rules_uncheck_to_pick_a_branch {
            get {
                return ResourceManager.GetString("Use_Is_Centralized_for_system_wide_rules_uncheck_to_pick_a_branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using ranges ensure no overlap..
        /// </summary>
        internal static string When_using_ranges_ensure_no_overlap {
            get {
                return ResourceManager.GetString("When_using_ranges_ensure_no_overlap", resourceCulture);
            }
        }
    }
}
