//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AffiliateToBranchFallback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AffiliateToBranchFallback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AffiliateToBranchFallback", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch accounts not available. Please try refreshing the page.
        /// </summary>
        internal static string Branch_accounts_not_available_Please_try_refreshing_the_page {
            get {
                return ResourceManager.GetString("Branch_accounts_not_available_Please_try_refreshing_the_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed information about the fallback transaction.
        /// </summary>
        internal static string Detailed_information_about_the_fallback_transaction {
            get {
                return ResourceManager.GetString("Detailed_information_about_the_fallback_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback GL Account.
        /// </summary>
        internal static string Fallback_GL_Account {
            get {
                return ResourceManager.GetString("Fallback_GL_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback GL Contains.
        /// </summary>
        internal static string Fallback_GL_Contains {
            get {
                return ResourceManager.GetString("Fallback_GL_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Log Details.
        /// </summary>
        internal static string Fallback_Log_Details {
            get {
                return ResourceManager.GetString("Fallback_Log_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Reconciliation.
        /// </summary>
        internal static string Fallback_Reconciliation {
            get {
                return ResourceManager.GetString("Fallback_Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and reconcile affiliate to branch fallback transactions.
        /// </summary>
        internal static string Manage_and_reconcile_affiliate_to_branch_fallback_transactions {
            get {
                return ResourceManager.GetString("Manage_and_reconcile_affiliate_to_branch_fallback_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile Fallback Transaction.
        /// </summary>
        internal static string Reconcile_Fallback_Transaction {
            get {
                return ResourceManager.GetString("Reconcile_Fallback_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconcile the fallback transaction by mapping source and destination GL accounts.
        /// </summary>
        internal static string Reconcile_the_fallback_transaction_by_mapping_source_and_destination_GL_accounts {
            get {
                return ResourceManager.GetString("Reconcile_the_fallback_transaction_by_mapping_source_and_destination_GL_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review and reconcile transactions that fell back to branch accounts.
        /// </summary>
        internal static string Review_and_reconcile_transactions_that_fell_back_to_branch_accounts {
            get {
                return ResourceManager.GetString("Review_and_reconcile_transactions_that_fell_back_to_branch_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supposed GL Account.
        /// </summary>
        internal static string Supposed_GL_Account {
            get {
                return ResourceManager.GetString("Supposed_GL_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supposed GL Contains.
        /// </summary>
        internal static string Supposed_GL_Contains {
            get {
                return ResourceManager.GetString("Supposed_GL_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account information content here.
        /// </summary>
        internal static string Your_account_information_content_here {
            get {
                return ResourceManager.GetString("Your_account_information_content_here", resourceCulture);
            }
        }
    }
}
