//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalTellerProvissioing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalTellerProvissioing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalTellerProvissioing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount provisioned.
        /// </summary>
        internal static string AmountProvisioned {
            get {
                return ResourceManager.GetString("AmountProvisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting provision to operations (Cashed to primary teller).
        /// </summary>
        internal static string AwaitingProvisionToOperationsCashedToPrimaryTeller {
            get {
                return ResourceManager.GetString("AwaitingProvisionToOperationsCashedToPrimaryTeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to provissioning listing.
        /// </summary>
        internal static string BackToProvissioningListing {
            get {
                return ResourceManager.GetString("BackToProvissioningListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation In Dinominations.
        /// </summary>
        internal static string ConfirmationInDinominations {
            get {
                return ResourceManager.GetString("ConfirmationInDinominations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter tellers in operation.
        /// </summary>
        internal static string FilterTellersInOperation {
            get {
                return ResourceManager.GetString("FilterTellersInOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIMARY TELLER PROVISSIONING.
        /// </summary>
        internal static string PRIMARY_TELLER_PROVISSIONING {
            get {
                return ResourceManager.GetString("PRIMARY_TELLER_PROVISSIONING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioing note.
        /// </summary>
        internal static string ProvisioingNote {
            get {
                return ResourceManager.GetString("ProvisioingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision (Open the day).
        /// </summary>
        internal static string ProvisionOpenTheDay {
            get {
                return ResourceManager.GetString("ProvisionOpenTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROVISSIONING SUB-TELLER.
        /// </summary>
        internal static string PROVISSIONING_SUB_TELLER {
            get {
                return ResourceManager.GetString("PROVISSIONING_SUB_TELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select branch.
        /// </summary>
        internal static string SelectBranch {
            get {
                return ResourceManager.GetString("SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select caisse to provision.
        /// </summary>
        internal static string SelectCaisseToProvision {
            get {
                return ResourceManager.GetString("SelectCaisseToProvision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select primary caisse.
        /// </summary>
        internal static string SelectPrimaryCaisse {
            get {
                return ResourceManager.GetString("SelectPrimaryCaisse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select primary teller.
        /// </summary>
        internal static string SelectPrimaryTeller {
            get {
                return ResourceManager.GetString("SelectPrimaryTeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select teller box.
        /// </summary>
        internal static string SelectTellerBox {
            get {
                return ResourceManager.GetString("SelectTellerBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user to manage the selected caisse.
        /// </summary>
        internal static string SelectUserToManageTheSelectedCaisse {
            get {
                return ResourceManager.GetString("SelectUserToManageTheSelectedCaisse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
    }
}
