//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMobileMoneyBackOffice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMobileMoneyBackOffice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalMobileMoneyBackOffice", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and credit those funds to the respective member&apos;s account.
        /// </summary>
        internal static string AndCreditThoseFundsToTheRespectiveMembersAccount {
            get {
                return ResourceManager.GetString("AndCreditThoseFundsToTheRespectiveMembersAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Office - None Cash Mobile Money Cash-In.
        /// </summary>
        internal static string BackOfficeNoneCashMobileMoneyCashIn {
            get {
                return ResourceManager.GetString("BackOfficeNoneCashMobileMoneyCashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK OFFICE - NONE CASH MOBILE MONEY CASH-IN.
        /// </summary>
        internal static string BACK_OFFICE_NONE_CASH_MOBILE_MONEY_CASH_IN {
            get {
                return ResourceManager.GetString("BACK_OFFICE_NONE_CASH_MOBILE_MONEY_CASH_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Ensure the deposit was made into the branch&apos;s Mobile Money Float Account** before processing.
        /// </summary>
        internal static string EnsureTheDepositWasMadeIntoTheBranchsMobileMoneyFloatAccount {
            get {
                return ResourceManager.GetString("EnsureTheDepositWasMadeIntoTheBranchsMobileMoneyFloatAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Enter a clear transaction note** specifying the reason for the cash-in.
        /// </summary>
        internal static string EnterAClearTransactionNote {
            get {
                return ResourceManager.GetString("EnterAClearTransactionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter member reference number.
        /// </summary>
        internal static string EnterMemberReferenceNumber {
            get {
                return ResourceManager.GetString("EnterMemberReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reason for transaction....
        /// </summary>
        internal static string EnterReasonForTransaction {
            get {
                return ResourceManager.GetString("EnterReasonForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 10-digit Member Reference Number. This includes a 3-digit Branch Code followed by a 7-digit Member Code.
        /// </summary>
        internal static string EnterThe10DigitMemberReferenceNumber {
            get {
                return ResourceManager.GetString("EnterThe10DigitMemberReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Enter the correct Teller Code** to process the cash-in transaction.
        /// </summary>
        internal static string EnterTheCorrectTellerCodeToProcess {
            get {
                return ResourceManager.GetString("EnterTheCorrectTellerCodeToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc.
        /// </summary>
        internal static string Inc {
            get {
                return ResourceManager.GetString("Inc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It allows staff to process **member deposits made into the branch&apos;s Mobile Money Float Account**.
        /// </summary>
        internal static string ItAllowsStaffToProcessMemberDeposits {
            get {
                return ResourceManager.GetString("ItAllowsStaffToProcessMemberDeposits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member&apos;s name.
        /// </summary>
        internal static string MembersName {
            get {
                return ResourceManager.GetString("MembersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/OM none member reference.
        /// </summary>
        internal static string MMOMNoneMemberReference {
            get {
                return ResourceManager.GetString("MMOMNoneMemberReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Money Cash-In Guidelines.
        /// </summary>
        internal static string MobileMoneyCashInGuidelines {
            get {
                return ResourceManager.GetString("MobileMoneyCashInGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile money MTN.
        /// </summary>
        internal static string MobileMoneyMTN {
            get {
                return ResourceManager.GetString("MobileMoneyMTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile money Orange.
        /// </summary>
        internal static string MobileMoneyOrange {
            get {
                return ResourceManager.GetString("MobileMoneyOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **No additional approval is required**, as the deposit was made directly by the member.
        /// </summary>
        internal static string NoAdditionalApprovalIsRequired {
            get {
                return ResourceManager.GetString("NoAdditionalApprovalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No withdrawals can be processed from this interface.
        /// </summary>
        internal static string NoWithdrawalsCanBeProcessedFromThisInterface {
            get {
                return ResourceManager.GetString("NoWithdrawalsCanBeProcessedFromThisInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once submitted, **transactions cannot be reversed without proper authorization**.
        /// </summary>
        internal static string OnceSubmittedTransactionsCannotBeReversed {
            get {
                return ResourceManager.GetString("OnceSubmittedTransactionsCannotBeReversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Only deposits (Cash-In) are allowed. Withdrawals cannot be processed from this interface.**.
        /// </summary>
        internal static string OnlyDepositsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyDepositsAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform secure cash deposits into member accounts. Follow the guidelines outlined in the Help Tips section above.
        /// </summary>
        internal static string PerformSecureCashDepositsIntoMemberAccounts {
            get {
                return ResourceManager.GetString("PerformSecureCashDepositsIntoMemberAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative name.
        /// </summary>
        internal static string RepresentativeName {
            get {
                return ResourceManager.GetString("RepresentativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Search for the member&apos;s account** using their **10-digit reference number**.
        /// </summary>
        internal static string SearchForTheMembersAccount {
            get {
                return ResourceManager.GetString("SearchForTheMembersAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Select the correct Mobile Money Operator (MTN or Orange)**.
        /// </summary>
        internal static string SelectTheCorrectMobileMoneyOperator {
            get {
                return ResourceManager.GetString("SelectTheCorrectMobileMoneyOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **The accountant must immediately process the transaction** by **crediting the member&apos;s account and debiting the float account.**.
        /// </summary>
        internal static string TheAccountantMustImmediatelyProcessTheTransaction {
            get {
                return ResourceManager.GetString("TheAccountantMustImmediatelyProcessTheTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This interface is exclusively for **back-office cash-in operations**.
        /// </summary>
        internal static string ThisInterfaceIsExclusivelyForBackOffice {
            get {
                return ResourceManager.GetString("ThisInterfaceIsExclusivelyForBackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till code.
        /// </summary>
        internal static string TillCode {
            get {
                return ResourceManager.GetString("TillCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Note (Reason).
        /// </summary>
        internal static string TransactionNoteReason {
            get {
                return ResourceManager.GetString("TransactionNoteReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Verify the amount entered, including any applicable fees, before confirming.**.
        /// </summary>
        internal static string VerifyTheAmountEnteredIncludingAnyApplicableFeesBeforeConfirming {
            get {
                return ResourceManager.GetString("VerifyTheAmountEnteredIncludingAnyApplicableFeesBeforeConfirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Verify the member&apos;s details** (Name, Telephone Number, and Member Reference) before proceeding.
        /// </summary>
        internal static string VerifyTheMembersDetails {
            get {
                return ResourceManager.GetString("VerifyTheMembersDetails", resourceCulture);
            }
        }
    }
}
