//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global_AddLoanCollateral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_AddLoanCollateral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global_AddLoanCollateral", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCollateral.
        /// </summary>
        internal static string AddCollateral {
            get {
                return ResourceManager.GetString("AddCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Collateral.
        /// </summary>
        internal static string AddNewCollateral {
            get {
                return ResourceManager.GetString("AddNewCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Category.
        /// </summary>
        internal static string CollateralCategory {
            get {
                return ResourceManager.GetString("CollateralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market value.
        /// </summary>
        internal static string Marketvalue {
            get {
                return ResourceManager.GetString("Marketvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Person Involved.
        /// </summary>
        internal static string NameOfPersonInvolved {
            get {
                return ResourceManager.GetString("NameOfPersonInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No loan collateral is added.
        /// </summary>
        internal static string NoLoanCollateralAdded {
            get {
                return ResourceManager.GetString("NoLoanCollateralAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate in percentage (%).
        /// </summary>
        internal static string RateInPercentage {
            get {
                return ResourceManager.GetString("RateInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Collaterals.
        /// </summary>
        internal static string ReloadCollaterals {
            get {
                return ResourceManager.GetString("ReloadCollaterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select loan collateral.
        /// </summary>
        internal static string SelectLoanCollateral {
            get {
                return ResourceManager.GetString("SelectLoanCollateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venal value.
        /// </summary>
        internal static string venalvalue {
            get {
                return ResourceManager.GetString("venalvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View List Of Collaterals.
        /// </summary>
        internal static string ViewListOfCollaterals {
            get {
                return ResourceManager.GetString("ViewListOfCollaterals", resourceCulture);
            }
        }
    }
}
