//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChartOfAccountV2Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChartOfAccountV2Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ChartOfAccountV2Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Hierarchy.
        /// </summary>
        internal static string Account_Hierarchy {
            get {
                return ResourceManager.GetString("Account_Hierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate Account Details.
        /// </summary>
        internal static string Affiliate_Account_Details {
            get {
                return ResourceManager.GetString("Affiliate_Account_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Chart of Accounts Management.
        /// </summary>
        internal static string Chart_of_Accounts_Management {
            get {
                return ResourceManager.GetString("Chart_of_Accounts_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose All/Active/Inactive — `All` will not filter by active state..
        /// </summary>
        internal static string Choose_All_Active_Inactive_All_will_not_filter_by_active_state {
            get {
                return ResourceManager.GetString("Choose_All_Active_Inactive_All_will_not_filter_by_active_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the caret to expand or collapse child nodes.
        /// </summary>
        internal static string Click_the_caret_to_expand_or_collapse_child_nodes {
            get {
                return ResourceManager.GetString("Click_the_caret_to_expand_or_collapse_child_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details &amp;amp; hierarchical structure for the selected node.
        /// </summary>
        internal static string Details_amp_hierarchical_structure_for_the_selected_node {
            get {
                return ResourceManager.GetString("Details_amp_hierarchical_structure_for_the_selected_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Chart Of Account Management.
        /// </summary>
        internal static string Edit_Chart_Of_Account_Management {
            get {
                return ResourceManager.GetString("Edit_Chart_Of_Account_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter and manage affiliates (search by code, name, status and creation date)..
        /// </summary>
        internal static string Filter_and_manage_affiliates_search_by_code_name_status_and_creation_date {
            get {
                return ResourceManager.GetString("Filter_and_manage_affiliates_search_by_code_name_status_and_creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the established numbering system for consistent account identification..
        /// </summary>
        internal static string Follow_the_established_numbering_system_for_consistent_account_identification {
            get {
                return ResourceManager.GetString("Follow_the_established_numbering_system_for_consistent_account_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Important: Changes to account structure may affect financial reporting and transactions..
        /// </summary>
        internal static string Important_Changes_to_account_structure_may_affect_financial_reporting_and_transactions {
            get {
                return ResourceManager.GetString("Important_Changes_to_account_structure_may_affect_financial_reporting_and_transac" +
                        "tions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain proper parent-child relationships for accurate financial reporting..
        /// </summary>
        internal static string Maintain_proper_parent_child_relationships_for_accurate_financial_reporting {
            get {
                return ResourceManager.GetString("Maintain_proper_parent_child_relationships_for_accurate_financial_reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Manage and organize your financial accounts hierarchy with ease. Display, edit, and maintain your chart of accounts structure..
        /// </summary>
        internal static string Manage_and_organize_your_financial_accounts_hierarchy_with_ease_Display_edit_and_maintain_your_chart_of_accounts_structure {
            get {
                return ResourceManager.GetString("Manage_and_organize_your_financial_accounts_hierarchy_with_ease_Display_edit_and_" +
                        "maintain_your_chart_of_accounts_structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches against affiliate name..
        /// </summary>
        internal static string Matches_against_affiliate_name {
            get {
                return ResourceManager.GetString("Matches_against_affiliate_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming Convention.
        /// </summary>
        internal static string Naming_Convention {
            get {
                return ResourceManager.GetString("Naming_Convention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only leaf-level accounts (with no children) should allow transaction posting..
        /// </summary>
        internal static string Only_leaf_level_accounts_with_no_children_should_allow_transaction_posting {
            get {
                return ResourceManager.GetString("Only_leaf_level_accounts_with_no_children_should_allow_transaction_posting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCMF CAMCULL Details.
        /// </summary>
        internal static string PCMF_CAMCULL_Details {
            get {
                return ResourceManager.GetString("PCMF_CAMCULL_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting nodes are labelled with a &lt;span class=&quot;badge bg-info&quot;&gt;Posting&lt;/span&gt; badge..
        /// </summary>
        internal static string Posting_nodes_are_labelled_with_a_Posting_badge {
            get {
                return ResourceManager.GetString("Posting_nodes_are_labelled_with_a_Posting_badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Rights.
        /// </summary>
        internal static string Posting_Rights {
            get {
                return ResourceManager.GetString("Posting_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Remember to save after making any modifications to account details..
        /// </summary>
        internal static string Remember_to_save_after_making_any_modifications_to_account_details {
            get {
                return ResourceManager.GetString("Remember_to_save_after_making_any_modifications_to_account_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an account to view details.
        /// </summary>
        internal static string Select_an_account_to_view_details {
            get {
                return ResourceManager.GetString("Select_an_account_to_view_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle date filters to limit by creation range (UTC).
        /// </summary>
        internal static string Toggle_date_filters_to_limit_by_creation_range_UTC {
            get {
                return ResourceManager.GetString("Toggle_date_filters_to_limit_by_creation_range_UTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Use clear and consistent naming in both English and French for all accounts..
        /// </summary>
        internal static string Use_clear_and_consistent_naming_in_both_English_and_French_for_all_accounts {
            get {
                return ResourceManager.GetString("Use_clear_and_consistent_naming_in_both_English_and_French_for_all_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &lt;em&gt;Expand&lt;/em&gt; and &lt;em&gt;Collapse&lt;/em&gt; to open/close all nodes quickly..
        /// </summary>
        internal static string Use_Expand_and_Collapse_to_open_close_all_nodes_quickly {
            get {
                return ResourceManager.GetString("Use_Expand_and_Collapse_to_open_close_all_nodes_quickly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use full or partial affiliate code for quick lookup..
        /// </summary>
        internal static string Use_full_or_partial_affiliate_code_for_quick_lookup {
            get {
                return ResourceManager.GetString("Use_full_or_partial_affiliate_code_for_quick_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the refresh button to ensure you&apos;re viewing the latest account structure.
        /// </summary>
        internal static string Use_the_refresh_button_to_ensure_you_re_viewing_the_latest_account_structure {
            get {
                return ResourceManager.GetString("Use_the_refresh_button_to_ensure_you_re_viewing_the_latest_account_structure", resourceCulture);
            }
        }
    }
}
