//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalNumConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalNumConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalNumConfig", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank/branch/year/serial positions control how numbers are built.
        /// </summary>
        internal static string bankbranchyearserial_positions_control_how_numbers_are_built {
            get {
                return ResourceManager.GetString("bankbranchyearserial_positions_control_how_numbers_are_built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code Pos.
        /// </summary>
        internal static string bank_code_pos {
            get {
                return ResourceManager.GetString("bank_code_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code Position.
        /// </summary>
        internal static string bank_code_position {
            get {
                return ResourceManager.GetString("bank_code_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code Pos.
        /// </summary>
        internal static string branch_code_pos {
            get {
                return ResourceManager.GetString("branch_code_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code Position.
        /// </summary>
        internal static string branch_code_position {
            get {
                return ResourceManager.GetString("branch_code_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Number Configurations.
        /// </summary>
        internal static string cheque_number_configurations {
            get {
                return ResourceManager.GetString("cheque_number_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Save&quot; to store your template. You can also &lt;strong&gt;Reset&lt;/strong&gt; to clear and start fresh.
        /// </summary>
        internal static string click_save_to_store_your_template_you_can_also_reset_to_clear_and_start_fresh {
            get {
                return ResourceManager.GetString("click_save_to_store_your_template_you_can_also_reset_to_clear_and_start_fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to components visually (drag to reorder). Drag-and-drop overrides numeric inputs automatically.
        /// </summary>
        internal static string components_visually_drag_to_reorder_draganddrop_overrides_numeric_inputs_automatically {
            get {
                return ResourceManager.GetString("components_visually_drag_to_reorder_draganddrop_overrides_numeric_inputs_automati" +
                        "cally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define and manage the structure of cheque number identifiers by arranging variables(Bank Code, Branch Code, Year, Serial Number).
        /// </summary>
        internal static string define_and_manage_the_structure_of_cheque_number_identifiers_by_arranging_variablesbank_code_branch_code_year_serial_number {
            get {
                return ResourceManager.GetString("define_and_manage_the_structure_of_cheque_number_identifiers_by_arranging_variabl" +
                        "esbank_code_branch_code_year_serial_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop.
        /// </summary>
        internal static string drag_drop {
            get {
                return ResourceManager.GetString("drag_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag placeholders (e.g. &lt;code&gt;{BranchCode}&lt;/code&gt;, &lt;code&gt;{Year}&lt;/code&gt;, &lt;code&gt;{Sequence}&lt;/code&gt;) in the template area to build your cheque number format.
        /// </summary>
        internal static string drag_placeholders_eg_branchcode_year_sequence_in_the_template_area_to_build_your_cheque_number_format {
            get {
                return ResourceManager.GetString("drag_placeholders_eg_branchcode_year_sequence_in_the_template_area_to_build_your_" +
                        "cheque_number_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag placeholders horizontally to adjust the order of fields in your cheque number.
        /// </summary>
        internal static string drag_placeholders_horizontally_to_adjust_the_order_of_fields_in_your_cheque_number {
            get {
                return ResourceManager.GetString("drag_placeholders_horizontally_to_adjust_the_order_of_fields_in_your_cheque_numbe" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure each required placeholder (like &lt;code&gt;{Sequence}&lt;/code&gt;) is included at least once.
        /// </summary>
        internal static string ensure_each_required_placeholder_like_sequence_is_included_at_least_once {
            get {
                return ResourceManager.GetString("ensure_each_required_placeholder_like_sequence_is_included_at_least_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage serial/number configuration per branch and date range.
        /// </summary>
        internal static string manage_serialnumber_configuration_per_branch_and_date_range {
            get {
                return ResourceManager.GetString("manage_serialnumber_configuration_per_branch_and_date_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Components &amp; Positions.
        /// </summary>
        internal static string number_components_positions {
            get {
                return ResourceManager.GetString("number_components_positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Configuration.
        /// </summary>
        internal static string number_configuration {
            get {
                return ResourceManager.GetString("number_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Config Filters.
        /// </summary>
        internal static string number_config_filters {
            get {
                return ResourceManager.GetString("number_config_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the branch to apply this numbering scheme.
        /// </summary>
        internal static string select_the_branch_to_apply_this_numbering_scheme {
            get {
                return ResourceManager.GetString("select_the_branch_to_apply_this_numbering_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number Position.
        /// </summary>
        internal static string serial_number_position {
            get {
                return ResourceManager.GetString("serial_number_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Pos.
        /// </summary>
        internal static string serial_pos {
            get {
                return ResourceManager.GetString("serial_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show numeric position inputs.
        /// </summary>
        internal static string show_numeric_position_inputs {
            get {
                return ResourceManager.GetString("show_numeric_position_inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template area shows your current format in real time.
        /// </summary>
        internal static string the_template_area_shows_your_current_format_in_real_time {
            get {
                return ResourceManager.GetString("the_template_area_shows_your_current_format_in_real_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Cheque Number Configuration.
        /// </summary>
        internal static string tips_for_cheque_number_configuration {
            get {
                return ResourceManager.GetString("tips_for_cheque_number_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips for Number Configuration.
        /// </summary>
        internal static string tips_for_number_configuration {
            get {
                return ResourceManager.GetString("tips_for_number_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date range to enable/disable configuration across time.
        /// </summary>
        internal static string use_date_range_to_enabledisable_configuration_across_time {
            get {
                return ResourceManager.GetString("use_date_range_to_enabledisable_configuration_across_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use drag-and-drop or dropdowns to control the order of variables in cheque numbers.
        /// </summary>
        internal static string use_draganddrop_or_dropdowns_to_control_the_order_of_variables_in_cheque_numbers {
            get {
                return ResourceManager.GetString("use_draganddrop_or_dropdowns_to_control_the_order_of_variables_in_cheque_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Pos.
        /// </summary>
        internal static string year_pos {
            get {
                return ResourceManager.GetString("year_pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Position.
        /// </summary>
        internal static string year_position {
            get {
                return ResourceManager.GetString("year_position", resourceCulture);
            }
        }
    }
}
