//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStandingOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStandingOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalStandingOrder", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account holder name.
        /// </summary>
        internal static string AccountHolderName {
            get {
                return ResourceManager.GetString("AccountHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account reference number.
        /// </summary>
        internal static string AccountReferenceNumber {
            get {
                return ResourceManager.GetString("AccountReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active status.
        /// </summary>
        internal static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new order.
        /// </summary>
        internal static string AddNewOrder {
            get {
                return ResourceManager.GetString("AddNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose realistic start and end dates to ensure seamless execution.
        /// </summary>
        internal static string ChooseRealisticStartAndEndDates {
            get {
                return ResourceManager.GetString("ChooseRealisticStartAndEndDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Create New Orders**: Click on the &quot;Add New Request&quot; button to initiate a standing order for a member directly from this page.
        /// </summary>
        internal static string CreateNewOrdersClickOnTheAddNewRequest {
            get {
                return ResourceManager.GetString("CreateNewOrdersClickOnTheAddNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination account.
        /// </summary>
        internal static string DestinationAccount {
            get {
                return ResourceManager.GetString("DestinationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination account type.
        /// </summary>
        internal static string DestinationAccountType {
            get {
                return ResourceManager.GetString("DestinationAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily create, view, and manage standing orders for members.
        /// </summary>
        internal static string EasilyCeateViewAndManageStandingOrdersForMembers {
            get {
                return ResourceManager.GetString("EasilyCeateViewAndManageStandingOrdersForMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Edit Existing Orders**: Locate the standing order using the search tool and click the &quot;Edit&quot; button to make updates or changes.
        /// </summary>
        internal static string EditExistingOrdersLocateTheStandingOrder {
            get {
                return ResourceManager.GetString("EditExistingOrdersLocateTheStandingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the account holder&apos;s name and reference number are accurate before submission.
        /// </summary>
        internal static string EnsureTheAccountHoldersName {
            get {
                return ResourceManager.GetString("EnsureTheAccountHoldersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter member reference number.
        /// </summary>
        internal static string EnterMemberReferenceNumber {
            get {
                return ResourceManager.GetString("EnterMemberReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed by system automatically.
        /// </summary>
        internal static string ExecutedBySystemAutomatically {
            get {
                return ResourceManager.GetString("ExecutedBySystemAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution type.
        /// </summary>
        internal static string ExecutionType {
            get {
                return ResourceManager.GetString("ExecutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External account.
        /// </summary>
        internal static string ExternalAccount {
            get {
                return ResourceManager.GetString("ExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External account holder name.
        /// </summary>
        internal static string ExternalAccountHolderName {
            get {
                return ResourceManager.GetString("ExternalAccountHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External account number.
        /// </summary>
        internal static string ExternalAccountNumber {
            get {
                return ResourceManager.GetString("ExternalAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If creating a standing order for loan repayment, ensure the balance covers the amount.
        /// </summary>
        internal static string IfCreatingAStandingOrderForLoanRepayment {
            get {
                return ResourceManager.GetString("IfCreatingAStandingOrderForLoanRepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If making payments to external accounts, double-check the account number and holder&apos;s name.
        /// </summary>
        internal static string IfMakingPaymentsToExternalAccounts {
            get {
                return ResourceManager.GetString("IfMakingPaymentsToExternalAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this order active.
        /// </summary>
        internal static string KeepThisOrderActive {
            get {
                return ResourceManager.GetString("KeepThisOrderActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make payment to an external account.
        /// </summary>
        internal static string MakePaymentToAnExternalAccount {
            get {
                return ResourceManager.GetString("MakePaymentToAnExternalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Member Communication**: Inform members about their active standing orders and encourage them to review details periodically.
        /// </summary>
        internal static string MemberCommunicationInformMembers {
            get {
                return ResourceManager.GetString("MemberCommunicationInformMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        internal static string MemberID {
            get {
                return ResourceManager.GetString("MemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name.
        /// </summary>
        internal static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **No Records Found?**: If no records are displayed, ensure you’ve entered the correct details in the search box or consider creating a new standing order if appropriate.
        /// </summary>
        internal static string NoRecordsFoundIfNoRecordsAreDisplayed {
            get {
                return ResourceManager.GetString("NoRecordsFoundIfNoRecordsAreDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No standing orders found.
        /// </summary>
        internal static string NoStandingOrdersFound {
            get {
                return ResourceManager.GetString("NoStandingOrdersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No standing orders found. Use the search box to find existing standing orders or create a new one.
        /// </summary>
        internal static string NoStandingOrdersFoundUseTheSearchBox {
            get {
                return ResourceManager.GetString("NoStandingOrdersFoundUseTheSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal note.
        /// </summary>
        internal static string PersonalNote {
            get {
                return ResourceManager.GetString("PersonalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularly review active standing orders to align with current financial needs.
        /// </summary>
        internal static string RegularlyReviewActiveStandingOrders {
            get {
                return ResourceManager.GetString("RegularlyReviewActiveStandingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Review Before Deleting**: Ensure you verify the member&apos;s details and purpose of the standing order before proceeding with deletion to avoid unintentional data loss.
        /// </summary>
        internal static string ReviewBeforeDeletingEnsureYouVerifyTheMembersDetails {
            get {
                return ResourceManager.GetString("ReviewBeforeDeletingEnsureYouVerifyTheMembersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search member reference.
        /// </summary>
        internal static string SearchMemberReference {
            get {
                return ResourceManager.GetString("SearchMemberReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Search Members Efficiently**: Use the search box to find a member and create or manage standing orders by entering the member&apos;s account reference number. This ensures you quickly locate the relevant record.
        /// </summary>
        internal static string SearchMembersEfficientlyUseTheSearchBoxToFindAMember {
            get {
                return ResourceManager.GetString("SearchMembersEfficientlyUseTheSearchBoxToFindAMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the &quot;Is Automatic&quot; option for system-managed execution if manual intervention is not required.
        /// </summary>
        internal static string SetTheIsAutomaticOptionForSystemManagedExecution {
            get {
                return ResourceManager.GetString("SetTheIsAutomaticOptionForSystemManagedExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source account.
        /// </summary>
        internal static string SourceAccount {
            get {
                return ResourceManager.GetString("SourceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source account type.
        /// </summary>
        internal static string SourceAccountType {
            get {
                return ResourceManager.GetString("SourceAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Order Details.
        /// </summary>
        internal static string StandingOrderDetails {
            get {
                return ResourceManager.GetString("StandingOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDING ORDER DETAILS.
        /// </summary>
        internal static string STANDING_ORDER_DETAILS {
            get {
                return ResourceManager.GetString("STANDING_ORDER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDING ORDER FORM.
        /// </summary>
        internal static string STANDING_ORDER_FORM {
            get {
                return ResourceManager.GetString("STANDING_ORDER_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STANDING ORDER MANAGEMENT.
        /// </summary>
        internal static string STANDING_ORDER_MANAGEMENT {
            get {
                return ResourceManager.GetString("STANDING_ORDER_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **System Notifications**: Use the notifications or reminders (if available) to keep track of pending or failed standing orders.
        /// </summary>
        internal static string SystemNotificationsUseTheNotifications {
            get {
                return ResourceManager.GetString("SystemNotificationsUseTheNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPS.
        /// </summary>
        internal static string TIPS {
            get {
                return ResourceManager.GetString("TIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Track Start and End Dates**: Regularly check the start and end dates of standing orders to ensure timely renewals or cancellations as needed.
        /// </summary>
        internal static string TrackStartAndEndDatesRegularlyCheckTheStartAndEndDates {
            get {
                return ResourceManager.GetString("TrackStartAndEndDatesRegularlyCheckTheStartAndEndDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use appropriate source and destination account types based on the standing order&apos;s purpose.
        /// </summary>
        internal static string UseAppropriateSourceAndDestinationAccountTypes {
            get {
                return ResourceManager.GetString("UseAppropriateSourceAndDestinationAccountTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &quot;Personal Note&quot; field to document the purpose or special instructions for the standing order.
        /// </summary>
        internal static string UseThePersonalNoteFieldToDocumentThePurpose {
            get {
                return ResourceManager.GetString("UseThePersonalNoteFieldToDocumentThePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage details of the standing order.
        /// </summary>
        internal static string ViewAndManageDetailsOfTheStandingOrder {
            get {
                return ResourceManager.GetString("ViewAndManageDetailsOfTheStandingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
